//
//  Language.swift
//  Univert
//
//  Created by Adrian Neshad on 2025-05-11.
//

import SwiftUI

class StringManager {
    static let shared = StringManager()
    @AppStorage("appLanguage") var language: String = "en"
    
    private let sv: [String: String] = [
        "settings": "Inställningar",
        "otherapps": "Andra appar",
        "univertfeedback": "Univert feedback",
        "givefeedback": "Ge feedback",
        "checkoutunivert": "Kolla in Univert appen!",
        "sharetheapp": "Dela appen",
        "ratetheapp": "Betygsätt appen",
        "about": "Om",
        "processing...": "Bearbetar...",
        "purchasecouldntrestore": "Inga köp kunde återställas",
        "restorefailed": "Återställning misslyckades",
        "purchaserestored": "Ditt köp har återställts",
        "restorepurchase": "Återställ köp",
        "advancedunitsunlocked": "Avancerade enheter upplåsta",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Avancerade enheter",
        "cancel": "Avbryt",
        "favoritescleared": "Favoriter rensade",
        "clear": "Rensa",
        "clearfavorites?": "Vill du rensa dina sparade favoriter?",
        "clearfavorites": "Rensa favoriter",
        "favorites": "Favoriter",
        "comma": "Komma decimalseparator",
        "darkmode": "Mörkt läge",
        "appearance": "Utseende",
        "notaddedfavorites": "Du har inte lagt till några favoriter än",
        "purchasefailed": "Köpet misslyckades, försök igen",
        "thanksforpurchase": "Tack för ditt köp!",
        "loading...": "Laddar...",
        "getaccess": "Få tillgång till alla avancerade enheter med ett engångsköp",
        "fluid": "Vätska",
        "electricity": "Elektricitet",
        "magnetism": "Magnetism",
        "monetaryunits": "Monetära enheter",
        "commonunits": "Vanliga enheter",
        "searchunits": "Sök enheter",
        "units": "Enheter",
        "from": "Från",
        "to": "till",
        "value": "Värde",
        "speed": "Hastighet",
        "addedtofavorites": "Tillagd i favoriter",
        "removed": "Borttagen",
        "source": "Källa: Europeiska Centralbanken (Frankfurter)",
        "source2": "Källa: CoinGecko",
        "invalidinput": "Ogiltigt värde",
        "radiation": "Strålning",
        "light": "Belysning",
        "language": "Språk",
        "data": "Data",
        "copied": "Kopierad",
        "unitOnCopy": "Enhet på kopierat värde",
        "unitOnCopyInfo": "Visa enhet med kopierat värde: 120 km/h",
        
        "unit_speed": "Hastighet",
        "unit_weight": "Vikt",
        "unit_length": "Längd",
        "unit_time": "Tid",
        "unit_temperature": "Temperatur",
        "unit_volume": "Volym",
        "unit_shoe_size": "Skostorlek",
        "unit_data_size": "Datastorlek",
        "unit_data_transfer_speed": "Dataöverföringshastighet",
        "unit_pressure": "Tryck",
        "unit_power": "Effekt",
        "unit_torque": "Vridmoment",
        "unit_currency": "Valuta",
        "unit_area": "Yta",
        "unit_crypto_beta": "Krypto (beta)",
        "unit_energy": "Energi",
        "unit_shares": "Kvot / Proportion",
        "unit_viscosity_dynamic": "Viskositet (dynamisk)",
        "unit_viscosity_kinematic": "Viskositet (kinematisk)",
        "unit_angles": "Vinklar",
        "unit_electric_current": "Elektrisk ström",
        "unit_electric_resistance": "Elektrisk resistans",
        "unit_numeral_system": "Talsystem",
        "unit_magnetomotive_force": "Magnetomotorisk kraft",
        "unit_magnetic_field_strength": "Magnetisk fältstyrka",
        "unit_magnetic_flux": "Magnetflöde",
        "unit_image_resolution": "Bildupplösning",
        "unit_inductance": "Induktans",
        "unit_charge": "Laddning",
        "unit_linear_charge": "Laddningstäthet (linjär)",
        "unit_volume_charge": "Laddningstäthet (volym)",
        "unit_surface_charge": "Laddningstäthet (yta)",
        "unit_magnetic_flux_density": "Magnetisk flödestäthet",
        "unit_radiation": "Strålning",
        "unit_radiation_activity": "Strålningsaktivitet",
        "unit_radiation_exposure": "Strålningsdos (exponering)",
        "unit_radiation_absorbed": "Strålning – Absorberad dos",
        "unit_linear_current": "Strömtäthet (linjär)",
        "unit_surface_tension": "Ytspänning",
        "unit_flow_rate": "Flöde",
        "unit_concentration_solution": "Lösningskoncentration",
        "unit_mass_flux_density": "Massflödestäthet",
        "unit_luminance": "Luminans",
        "unit_luminous_intensity": "Ljusstyrka",
        "unit_luminous_flux": "Ljusflöde",
        "unit_illuminance": "Belysning",
        "unit_frequency": "Frekvens",
        "unit_fuel_consumption": "Bränsleförbrukning",
    ]
    
    private let en: [String: String] = [
        "settings": "Settings",
        "otherapps": "Other apps",
        "univertfeedback": "Univert feedback",
        "givefeedback": "Give feedback",
        "checkoutunivert": "Check out the Univert app!",
        "sharetheapp": "Share the app",
        "ratetheapp": "Rate the app",
        "about": "About",
        "processing...": "Processing...",
        "purchasecouldntrestore": "No purchases could be restored",
        "restorefailed": "Restore failed",
        "purchaserestored": "Your purchase has been restored",
        "restorepurchase": "Restore purchase",
        "advancedunitsunlocked": "Advanced units unlocked",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Advanced units",
        "cancel": "Cancel",
        "favoritescleared": "Favorites cleared",
        "clear": "Clear",
        "clearfavorites?": "Do you want to clear your saved favorites?",
        "clearfavorites": "Clear favorites",
        "favorites": "Favorites",
        "comma": "Comma decimal separator",
        "darkmode": "Dark mode",
        "appearance": "Appearance",
        "notaddedfavorites": "You haven't added any favorites yet",
        "purchasefailed": "Purchase failed, please try again",
        "thanksforpurchase": "Thanks for your purchase!",
        "loading...": "Loading...",
        "getaccess": "Get access to all advanced units with a one-time purchase",
        "fluid": "Fluid",
        "electricity": "Electricity",
        "magnetism": "Magnetism",
        "monetaryunits": "Monetary units",
        "commonunits": "Common units",
        "searchunits": "Search units",
        "units": "Units",
        "from": "From",
        "to": "to",
        "value": "Value",
        "speed": "Speed",
        "addedtofavorites": "Added to favorites",
        "removed": "Removed",
        "source": "Source: European Central Bank (Frankfurter)",
        "source2": "Source: CoinGecko",
        "invalidinput": "Invalid value",
        "radiation": "Radiation",
        "light": "Lighting",
        "language": "Language",
        "data": "Data",
        "copied": "Copied",
        "unitOnCopy": "Unit on copied value",
        "unitOnCopyInfo": "Show unit on copied value: 120 km/h",
        
        "unit_speed": "Speed",
        "unit_weight": "Weight",
        "unit_length": "Length",
        "unit_time": "Time",
        "unit_temperature": "Temperature",
        "unit_volume": "Volume",
        "unit_shoe_size": "Shoe Size",
        "unit_data_size": "Data Size",
        "unit_data_transfer_speed": "Data Transfer Speed",
        "unit_pressure": "Pressure",
        "unit_power": "Power",
        "unit_torque": "Torque",
        "unit_currency": "Currency",
        "unit_area": "Area",
        "unit_crypto_beta": "Crypto (beta)",
        "unit_energy": "Energy",
        "unit_shares": "Ratio / Proportion",
        "unit_viscosity_dynamic": "Viscosity (dynamic)",
        "unit_viscosity_kinematic": "Viscosity (kinematic)",
        "unit_angles": "Angles",
        "unit_electric_current": "Electric Current",
        "unit_electric_resistance": "Electric Resistance",
        "unit_numeral_system": "Numeral System",
        "unit_magnetomotive_force": "Magnetomotive Force",
        "unit_magnetic_field_strength": "Magnetic Field Strength",
        "unit_magnetic_flux": "Magnetic Flux",
        "unit_image_resolution": "Image Resolution",
        "unit_inductance": "Inductance",
        "unit_charge": "Charge",
        "unit_linear_charge": "Linear Charge Density",
        "unit_volume_charge": "Volume Charge Density",
        "unit_surface_charge": "Surface Charge Density",
        "unit_magnetic_flux_density": "Magnetic Flux Density",
        "unit_radiation": "Radiation",
        "unit_radiation_activity": "Radiation Activity",
        "unit_radiation_exposure": "Radiation Exposure",
        "unit_radiation_absorbed": "Radiation – Absorbed Dose",
        "unit_linear_current": "Linear Current Density",
        "unit_surface_tension": "Surface Tension",
        "unit_flow_rate": "Flow Rate",
        "unit_concentration_solution": "Concentration (solution)",
        "unit_mass_flux_density": "Mass Flux Density",
        "unit_luminance": "Luminance",
        "unit_luminous_intensity": "Luminous Intensity",
        "unit_luminous_flux": "Luminous Flux",
        "unit_illuminance": "Illuminance",
        "unit_frequency": "Frequency",
        "unit_fuel_consumption": "Fuel Consumption",
    ]
    
    private let de: [String: String] = [
        "settings": "Einstellungen",
        "otherapps": "Andere Apps",
        "univertfeedback": "Univert Feedback",
        "givefeedback": "Feedback geben",
        "checkoutunivert": "Univert-App ansehen!",
        "sharetheapp": "App teilen",
        "ratetheapp": "App bewerten",
        "about": "Über",
        "processing...": "Verarbeitung...",
        "purchasecouldntrestore": "Käufe konnten nicht wiederhergestellt werden",
        "restorefailed": "Wiederherstellung fehlgeschlagen",
        "purchaserestored": "Ihr Kauf wurde wiederhergestellt",
        "restorepurchase": "Kauf wiederherstellen",
        "advancedunitsunlocked": "Erweiterte Einheiten freigeschaltet",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Erweiterte Einheiten",
        "cancel": "Abbrechen",
        "favoritescleared": "Favoriten gelöscht",
        "clear": "Löschen",
        "clearfavorites?": "Möchten Sie Ihre gespeicherten Favoriten löschen?",
        "clearfavorites": "Favoriten löschen",
        "favorites": "Favoriten",
        "comma": "Komma als Dezimaltrennzeichen",
        "darkmode": "Dunkler Modus",
        "appearance": "Erscheinungsbild",
        "notaddedfavorites": "Sie haben noch keine Favoriten hinzugefügt",
        "purchasefailed": "Kauf fehlgeschlagen, bitte erneut versuchen",
        "thanksforpurchase": "Danke für Ihren Kauf!",
        "loading...": "Lädt...",
        "getaccess": "Zugang zu allen erweiterten Einheiten mit einem einmaligen Kauf",
        "fluid": "Flüssigkeit",
        "electricity": "Elektrizität",
        "magnetism": "Magnetismus",
        "monetaryunits": "Währungseinheiten",
        "commonunits": "Allgemeine Einheiten",
        "searchunits": "Einheiten suchen",
        "units": "Einheiten",
        "from": "Von",
        "to": "bis",
        "value": "Wert",
        "speed": "Geschwindigkeit",
        "addedtofavorites": "Zu Favoriten hinzugefügt",
        "removed": "Entfernt",
        "source": "Quelle: Europäische Zentralbank (Frankfurter)",
        "source2": "Quelle: CoinGecko",
        "invalidinput": "Ungültiger Wert",
        "radiation": "Strahlung",
        "light": "Beleuchtung",
        "language": "Sprache",
        "data": "Daten",
        "copied": "Kopiert",
        "unitOnCopy": "Einheit beim Kopieren",
        "unitOnCopyInfo": "Einheit mit kopiertem Wert anzeigen: 120 km/h",

        "unit_speed": "Geschwindigkeit",
        "unit_weight": "Gewicht",
        "unit_length": "Länge",
        "unit_time": "Zeit",
        "unit_temperature": "Temperatur",
        "unit_volume": "Volumen",
        "unit_shoe_size": "Schuhgröße",
        "unit_data_size": "Datenmenge",
        "unit_data_transfer_speed": "Datenübertragungsrate",
        "unit_pressure": "Druck",
        "unit_power": "Leistung",
        "unit_torque": "Drehmoment",
        "unit_currency": "Währung",
        "unit_area": "Fläche",
        "unit_crypto_beta": "Krypto (Beta)",
        "unit_energy": "Energie",
        "unit_shares": "Verhältnis / Proportion",
        "unit_viscosity_dynamic": "Dynamische Viskosität",
        "unit_viscosity_kinematic": "Kinematische Viskosität",
        "unit_angles": "Winkel",
        "unit_electric_current": "Elektrischer Strom",
        "unit_electric_resistance": "Elektrischer Widerstand",
        "unit_numeral_system": "Zahlensystem",
        "unit_magnetomotive_force": "Magnetomotorische Kraft",
        "unit_magnetic_field_strength": "Magnetfeldstärke",
        "unit_magnetic_flux": "Magnetischer Fluss",
        "unit_image_resolution": "Bildauflösung",
        "unit_inductance": "Induktivität",
        "unit_charge": "Ladung",
        "unit_linear_charge": "Lineare Ladungsdichte",
        "unit_volume_charge": "Volumenladungsdichte",
        "unit_surface_charge": "Oberflächenladungsdichte",
        "unit_magnetic_flux_density": "Magnetische Flussdichte",
        "unit_radiation": "Strahlung",
        "unit_radiation_activity": "Aktivität der Strahlung",
        "unit_radiation_exposure": "Strahlenexposition",
        "unit_radiation_absorbed": "Strahlung – Absorbierte Dosis",
        "unit_linear_current": "Lineare Stromdichte",
        "unit_surface_tension": "Oberflächenspannung",
        "unit_flow_rate": "Durchflussrate",
        "unit_concentration_solution": "Konzentration (Lösung)",
        "unit_mass_flux_density": "Massenflussdichte",
        "unit_luminance": "Leuchtdichte",
        "unit_luminous_intensity": "Lichtstärke",
        "unit_luminous_flux": "Lichtstrom",
        "unit_illuminance": "Beleuchtungsstärke",
        "unit_frequency": "Frequenz",
        "unit_fuel_consumption": "Kraftstoffverbrauch",
    ]
    
    private let es: [String: String] = [
        "settings": "Configuración",
        "otherapps": "Otras apps",
        "univertfeedback": "Comentarios de Univert",
        "givefeedback": "Dar comentarios",
        "checkoutunivert": "¡Mira la app Univert!",
        "sharetheapp": "Compartir app",
        "ratetheapp": "Calificar app",
        "about": "Acerca de",
        "processing...": "Procesando...",
        "purchasecouldntrestore": "No se pudieron restaurar las compras",
        "restorefailed": "Error al restaurar",
        "purchaserestored": "Tu compra ha sido restaurada",
        "restorepurchase": "Restaurar compra",
        "advancedunitsunlocked": "Unidades avanzadas desbloqueadas",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Unidades avanzadas",
        "cancel": "Cancelar",
        "favoritescleared": "Favoritos eliminados",
        "clear": "Limpiar",
        "clearfavorites?": "¿Deseas eliminar tus favoritos guardados?",
        "clearfavorites": "Eliminar favoritos",
        "favorites": "Favoritos",
        "comma": "Separador decimal con coma",
        "darkmode": "Modo oscuro",
        "appearance": "Apariencia",
        "notaddedfavorites": "Aún no has añadido favoritos",
        "purchasefailed": "La compra ha fallado, inténtalo de nuevo",
        "thanksforpurchase": "¡Gracias por tu compra!",
        "loading...": "Cargando...",
        "getaccess": "Accede a todas las unidades avanzadas con una compra única",
        "fluid": "Fluido",
        "electricity": "Electricidad",
        "magnetism": "Magnetismo",
        "monetaryunits": "Unidades monetarias",
        "commonunits": "Unidades comunes",
        "searchunits": "Buscar unidades",
        "units": "Unidades",
        "from": "De",
        "to": "a",
        "value": "Valor",
        "speed": "Velocidad",
        "addedtofavorites": "Agregado a favoritos",
        "removed": "Eliminado",
        "source": "Fuente: Banco Central Europeo (Frankfurter)",
        "source2": "Fuente: CoinGecko",
        "invalidinput": "Valor inválido",
        "radiation": "Radiación",
        "light": "Iluminación",
        "language": "Idioma",
        "data": "Datos",
        "copied": "Copiado",
        "unitOnCopy": "Unidad al copiar valor",
        "unitOnCopyInfo": "Mostrar unidad con el valor copiado: 120 km/h",

        "unit_speed": "Velocidad",
        "unit_weight": "Peso",
        "unit_length": "Longitud",
        "unit_time": "Tiempo",
        "unit_temperature": "Temperatura",
        "unit_volume": "Volumen",
        "unit_shoe_size": "Talla de zapato",
        "unit_data_size": "Tamaño de datos",
        "unit_data_transfer_speed": "Velocidad de transferencia de datos",
        "unit_pressure": "Presión",
        "unit_power": "Potencia",
        "unit_torque": "Par",
        "unit_currency": "Moneda",
        "unit_area": "Área",
        "unit_crypto_beta": "Cripto (beta)",
        "unit_energy": "Energía",
        "unit_shares": "Relación / Proporción",
        "unit_viscosity_dynamic": "Viscosidad dinámica",
        "unit_viscosity_kinematic": "Viscosidad cinemática",
        "unit_angles": "Ángulos",
        "unit_electric_current": "Corriente eléctrica",
        "unit_electric_resistance": "Resistencia eléctrica",
        "unit_numeral_system": "Sistema numérico",
        "unit_magnetomotive_force": "Fuerza magnetomotriz",
        "unit_magnetic_field_strength": "Intensidad de campo magnético",
        "unit_magnetic_flux": "Flujo magnético",
        "unit_image_resolution": "Resolución de imagen",
        "unit_inductance": "Inductancia",
        "unit_charge": "Carga",
        "unit_linear_charge": "Densidad lineal de carga",
        "unit_volume_charge": "Densidad de carga volumétrica",
        "unit_surface_charge": "Densidad de carga superficial",
        "unit_magnetic_flux_density": "Densidad de flujo magnético",
        "unit_radiation": "Radiación",
        "unit_radiation_activity": "Actividad radiactiva",
        "unit_radiation_exposure": "Exposición a la radiación",
        "unit_radiation_absorbed": "Radiación – Dosis absorbida",
        "unit_linear_current": "Densidad de corriente lineal",
        "unit_surface_tension": "Tensión superficial",
        "unit_flow_rate": "Caudal",
        "unit_concentration_solution": "Concentración (solución)",
        "unit_mass_flux_density": "Densidad de flujo de masa",
        "unit_luminance": "Luminancia",
        "unit_luminous_intensity": "Intensidad luminosa",
        "unit_luminous_flux": "Flujo luminoso",
        "unit_illuminance": "Iluminancia",
        "unit_frequency": "Frecuencia",
        "unit_fuel_consumption": "Consumo de combustible",
    ]
    
    private let fr: [String: String] = [
        "settings": "Paramètres",
        "otherapps": "Autres applications",
        "univertfeedback": "Retour Univert",
        "givefeedback": "Donner un retour",
        "checkoutunivert": "Découvrez l’app Univert !",
        "sharetheapp": "Partager l’application",
        "ratetheapp": "Noter l’application",
        "about": "À propos",
        "processing...": "Traitement...",
        "purchasecouldntrestore": "Impossible de restaurer les achats",
        "restorefailed": "Échec de la restauration",
        "purchaserestored": "Votre achat a été restauré",
        "restorepurchase": "Restaurer l’achat",
        "advancedunitsunlocked": "Unités avancées déverrouillées",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Unités avancées",
        "cancel": "Annuler",
        "favoritescleared": "Favoris effacés",
        "clear": "Effacer",
        "clearfavorites?": "Souhaitez-vous effacer vos favoris enregistrés ?",
        "clearfavorites": "Effacer les favoris",
        "favorites": "Favoris",
        "comma": "Séparateur décimal virgule",
        "darkmode": "Mode sombre",
        "appearance": "Apparence",
        "notaddedfavorites": "Vous n’avez encore ajouté aucun favori",
        "purchasefailed": "Échec de l’achat, veuillez réessayer",
        "thanksforpurchase": "Merci pour votre achat !",
        "loading...": "Chargement...",
        "getaccess": "Accédez à toutes les unités avancées avec un achat unique",
        "fluid": "Fluide",
        "electricity": "Électricité",
        "magnetism": "Magnétisme",
        "monetaryunits": "Unités monétaires",
        "commonunits": "Unités courantes",
        "searchunits": "Rechercher des unités",
        "units": "Unités",
        "from": "De",
        "to": "à",
        "value": "Valeur",
        "speed": "Vitesse",
        "addedtofavorites": "Ajouté aux favoris",
        "removed": "Supprimé",
        "source": "Source : Banque centrale européenne (Frankfurter)",
        "source2": "Source : CoinGecko",
        "invalidinput": "Valeur invalide",
        "radiation": "Rayonnement",
        "light": "Éclairage",
        "language": "Langue",
        "data": "Données",
        "copied": "Copié",
        "unitOnCopy": "Unité lors de la copie",
        "unitOnCopyInfo": "Afficher l'unité avec la valeur copiée : 120 km/h",

        "unit_speed": "Vitesse",
        "unit_weight": "Poids",
        "unit_length": "Longueur",
        "unit_time": "Temps",
        "unit_temperature": "Température",
        "unit_volume": "Volume",
        "unit_shoe_size": "Pointure",
        "unit_data_size": "Taille des données",
        "unit_data_transfer_speed": "Vitesse de transfert de données",
        "unit_pressure": "Pression",
        "unit_power": "Puissance",
        "unit_torque": "Couple",
        "unit_currency": "Devise",
        "unit_area": "Surface",
        "unit_crypto_beta": "Crypto (bêta)",
        "unit_energy": "Énergie",
        "unit_shares": "Rapport / Proportion",
        "unit_viscosity_dynamic": "Viscosité dynamique",
        "unit_viscosity_kinematic": "Viscosité cinématique",
        "unit_angles": "Angles",
        "unit_electric_current": "Courant électrique",
        "unit_electric_resistance": "Résistance électrique",
        "unit_numeral_system": "Système numérique",
        "unit_magnetomotive_force": "Force magnétomotrice",
        "unit_magnetic_field_strength": "Intensité du champ magnétique",
        "unit_magnetic_flux": "Flux magnétique",
        "unit_image_resolution": "Résolution d’image",
        "unit_inductance": "Inductance",
        "unit_charge": "Charge",
        "unit_linear_charge": "Densité linéique de charge",
        "unit_volume_charge": "Densité volumique de charge",
        "unit_surface_charge": "Densité surfacique de charge",
        "unit_magnetic_flux_density": "Densité de flux magnétique",
        "unit_radiation": "Rayonnement",
        "unit_radiation_activity": "Activité radioactive",
        "unit_radiation_exposure": "Exposition aux radiations",
        "unit_radiation_absorbed": "Rayonnement – Dose absorbée",
        "unit_linear_current": "Densité de courant linéaire",
        "unit_surface_tension": "Tension superficielle",
        "unit_flow_rate": "Débit",
        "unit_concentration_solution": "Concentration (solution)",
        "unit_mass_flux_density": "Densité de flux de masse",
        "unit_luminance": "Luminance",
        "unit_luminous_intensity": "Intensité lumineuse",
        "unit_luminous_flux": "Flux lumineux",
        "unit_illuminance": "Éclairement",
        "unit_frequency": "Fréquence",
        "unit_fuel_consumption": "Consommation de carburant",
    ]

    private let he: [String: String] = [ // Hebreiska
        "settings": "הגדרות",
        "otherapps": "אפליקציות אחרות",
        "univertfeedback": "משוב Univert",
        "givefeedback": "תן משוב",
        "checkoutunivert": "בדוק את אפליקציית Univert!",
        "sharetheapp": "שתף את האפליקציה",
        "ratetheapp": "דרג את האפליקציה",
        "about": "אודות",
        "processing...": "מעבד...",
        "purchasecouldntrestore": "לא ניתן לשחזר רכישות",
        "restorefailed": "שחזור נכשל",
        "purchaserestored": "הרכישה שלך שוחזרה",
        "restorepurchase": "שחזר רכישה",
        "advancedunitsunlocked": "יחידות מתקדמות נפתחו",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "יחידות מתקדמות",
        "cancel": "בטל",
        "favoritescleared": "מועדפים נוקו",
        "clear": "נקה",
        "clearfavorites?": "האם ברצונך לנקות את המועדפים השמורים שלך?",
        "clearfavorites": "נקה מועדפים",
        "favorites": "מועדפים",
        "comma": "פסיק כמפריד עשרוני",
        "darkmode": "מצב כהה",
        "appearance": "מראה",
        "notaddedfavorites": "טרם הוספת מועדפים",
        "purchasefailed": "הרכישה נכשלה, אנא נסה שוב",
        "thanksforpurchase": "תודה על רכישתך!",
        "loading...": "טוען...",
        "getaccess": "קבל גישה לכל היחידות המתקדמות עם רכישה חד-פעמית",
        "fluid": "נוזל",
        "electricity": "חשמל",
        "magnetism": "מגנטיות",
        "monetaryunits": "יחידות כספיות",
        "commonunits": "יחידות נפוצות",
        "searchunits": "חפש יחידות",
        "units": "יחידות",
        "from": "מ",
        "to": "ל",
        "value": "ערך",
        "speed": "מהירות",
        "addedtofavorites": "נוסף למועדפים",
        "removed": "הוסר",
        "source": "מקור: הבנק המרכזי האירופי (Frankfurter)",
        "source2": "מקור: CoinGecko",
        "invalidinput": "קלט לא חוקי",
        "radiation": "קרינה",
        "light": "תאורה",
        "language": "שפה",
        "data": "נתונים",
        "copied": "הועתק",
        "unitOnCopy": "יחידה בהעתקה",
        "unitOnCopyInfo": "הצג יחידה עם הערך המועתק: 120 קמ\"ש",

        "unit_speed": "מהירות",
        "unit_weight": "משקל",
        "unit_length": "אורך",
        "unit_time": "זמן",
        "unit_temperature": "טמפרטורה",
        "unit_volume": "נפח",
        "unit_shoe_size": "מידת נעליים",
        "unit_data_size": "גודל נתונים",
        "unit_data_transfer_speed": "מהירות העברת נתונים",
        "unit_pressure": "לחץ",
        "unit_power": "הספק",
        "unit_torque": "מומנט",
        "unit_currency": "מטבע",
        "unit_area": "שטח",
        "unit_crypto_beta": "קריפטו (beta)",
        "unit_energy": "אנרגיה",
        "unit_shares": "יחס / פרופורציה",
        "unit_viscosity_dynamic": "צמיגות (דינמית)",
        "unit_viscosity_kinematic": "צמיגות (קינמטית)",
        "unit_angles": "זוויות",
        "unit_electric_current": "זרם חשמלי",
        "unit_electric_resistance": "התנגדות חשמלית",
        "unit_numeral_system": "מערכת מספרים",
        "unit_magnetomotive_force": "כוח מגנטו-מוטורי",
        "unit_magnetic_field_strength": "עוצמת שדה מגנטי",
        "unit_magnetic_flux": "שטף מגנטי",
        "unit_image_resolution": "רזולוציית תמונה",
        "unit_inductance": "השראות",
        "unit_charge": "מטען",
        "unit_linear_charge": "צפיפות מטען ליניארית",
        "unit_volume_charge": "צפיפות מטען נפחית",
        "unit_surface_charge": "צפיפות מטען פני השטח",
        "unit_magnetic_flux_density": "צפיפות שטף מגנטי",
        "unit_radiation": "קרינה",
        "unit_radiation_activity": "פעילות קרינה",
        "unit_radiation_exposure": "חשיפה לקרינה",
        "unit_radiation_absorbed": "קרינה – מינון נספג",
        "unit_linear_current": "צפיפות זרם ליניארית",
        "unit_surface_tension": "מתח פנים",
        "unit_flow_rate": "קצב זרימה",
        "unit_concentration_solution": "ריכוז (תמיסה)",
        "unit_mass_flux_density": "צפיפות שטף מסה",
        "unit_luminance": "בהיקות",
        "unit_luminous_intensity": "עוצמת אור",
        "unit_luminous_flux": "שטף אור",
        "unit_illuminance": "עוצמת הארה",
        "unit_frequency": "תדירות",
        "unit_fuel_consumption": "צריכת דלק",
    ]

    private let zh: [String: String] = [ // Kinesiska (Mandarin, förenklad)
        "settings": "设置",
        "otherapps": "其他应用",
        "univertfeedback": "Univert 反馈",
        "givefeedback": "提供反馈",
        "checkoutunivert": "查看 Univert 应用！",
        "sharetheapp": "分享应用",
        "ratetheapp": "评价应用",
        "about": "关于",
        "processing...": "处理中...",
        "purchasecouldntrestore": "无法恢复购买",
        "restorefailed": "恢复失败",
        "purchaserestored": "您的购买已恢复",
        "restorepurchase": "恢复购买",
        "advancedunitsunlocked": "高级单位已解锁",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "高级单位",
        "cancel": "取消",
        "favoritescleared": "收藏夹已清空",
        "clear": "清空",
        "clearfavorites?": "您要清空已保存的收藏夹吗？",
        "clearfavorites": "清空收藏夹",
        "favorites": "收藏夹",
        "comma": "逗号作小数分隔符",
        "darkmode": "深色模式",
        "appearance": "外观",
        "notaddedfavorites": "您还没有添加任何收藏",
        "purchasefailed": "购买失败，请重试",
        "thanksforpurchase": "感谢您的购买！",
        "loading...": "加载中...",
        "getaccess": "一次性购买即可访问所有高级单位",
        "fluid": "流体",
        "electricity": "电力",
        "magnetism": "磁学",
        "monetaryunits": "货币单位",
        "commonunits": "常用单位",
        "searchunits": "搜索单位",
        "units": "单位",
        "from": "从",
        "to": "到",
        "value": "值",
        "speed": "速度",
        "addedtofavorites": "已添加到收藏夹",
        "removed": "已移除",
        "source": "来源：欧洲中央银行（Frankfurter）",
        "source2": "来源：CoinGecko",
        "invalidinput": "无效输入",
        "radiation": "辐射",
        "light": "照明",
        "language": "语言",
        "data": "数据",
        "copied": "已复制",
        "unitOnCopy": "复制时包含单位",
        "unitOnCopyInfo": "显示带单位的复制值：120 km/h",

        "unit_speed": "速度",
        "unit_weight": "重量",
        "unit_length": "长度",
        "unit_time": "时间",
        "unit_temperature": "温度",
        "unit_volume": "体积",
        "unit_shoe_size": "鞋码",
        "unit_data_size": "数据大小",
        "unit_data_transfer_speed": "数据传输速度",
        "unit_pressure": "压力",
        "unit_power": "功率",
        "unit_torque": "扭矩",
        "unit_currency": "货币",
        "unit_area": "面积",
        "unit_crypto_beta": "加密货币 (beta)",
        "unit_energy": "能量",
        "unit_shares": "比率 / 比例",
        "unit_viscosity_dynamic": "粘度 (动态)",
        "unit_viscosity_kinematic": "粘度 (运动)",
        "unit_angles": "角度",
        "unit_electric_current": "电流",
        "unit_electric_resistance": "电阻",
        "unit_numeral_system": "数字系统",
        "unit_magnetomotive_force": "磁动势",
        "unit_magnetic_field_strength": "磁场强度",
        "unit_magnetic_flux": "磁通量",
        "unit_image_resolution": "图像分辨率",
        "unit_inductance": "电感",
        "unit_charge": "电荷",
        "unit_linear_charge": "线电荷密度",
        "unit_volume_charge": "体电荷密度",
        "unit_surface_charge": "面电荷密度",
        "unit_magnetic_flux_density": "磁通量密度",
        "unit_radiation": "辐射",
        "unit_radiation_activity": "放射性活度",
        "unit_radiation_exposure": "辐射暴露",
        "unit_radiation_absorbed": "辐射 – 吸收剂量",
        "unit_linear_current": "线电流密度",
        "unit_surface_tension": "表面张力",
        "unit_flow_rate": "流量",
        "unit_concentration_solution": "浓度 (溶液)",
        "unit_mass_flux_density": "质量通量密度",
        "unit_luminance": "亮度",
        "unit_luminous_intensity": "发光强度",
        "unit_luminous_flux": "光通量",
        "unit_illuminance": "照度",
        "unit_frequency": "频率",
        "unit_fuel_consumption": "燃料消耗",
    ]

    private let ar: [String: String] = [ // Arabiska
        "settings": "الإعدادات",
        "otherapps": "تطبيقات أخرى",
        "univertfeedback": "ملاحظات Univert",
        "givefeedback": "إرسال ملاحظات",
        "checkoutunivert": "تحقق من تطبيق Univert!",
        "sharetheapp": "مشاركة التطبيق",
        "ratetheapp": "تقييم التطبيق",
        "about": "حول",
        "processing...": "جارٍ المعالجة...",
        "purchasecouldntrestore": "لا يمكن استعادة عمليات الشراء",
        "restorefailed": "فشل الاستعادة",
        "purchaserestored": "تمت استعادة عملية الشراء الخاصة بك",
        "restorepurchase": "استعادة الشراء",
        "advancedunitsunlocked": "الوحدات المتقدمة مفتوحة",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "الوحدات المتقدمة",
        "cancel": "إلغاء",
        "favoritescleared": "تم مسح المفضلة",
        "clear": "مسح",
        "clearfavorites?": "هل تريد مسح مفضلاتك المحفوظة؟",
        "clearfavorites": "مسح المفضلة",
        "favorites": "المفضلة",
        "comma": "فاصلة كفاصل عشري",
        "darkmode": "الوضع الداكن",
        "appearance": "المظهر",
        "notaddedfavorites": "لم تقم بإضافة أي مفضلات بعد",
        "purchasefailed": "فشل الشراء، يرجى المحاولة مرة أخرى",
        "thanksforpurchase": "شكرا لك على شرائك!",
        "loading...": "جارٍ التحميل...",
        "getaccess": "احصل على إمكانية الوصول إلى جميع الوحدات المتقدمة بعملية شراء لمرة واحدة",
        "fluid": "سائل",
        "electricity": "كهرباء",
        "magnetism": "مغناطيسية",
        "monetaryunits": "وحدات نقدية",
        "commonunits": "وحدات شائعة",
        "searchunits": "بحث الوحدات",
        "units": "الوحدات",
        "from": "من",
        "to": "إلى",
        "value": "القيمة",
        "speed": "السرعة",
        "addedtofavorites": "تمت الإضافة إلى المفضلة",
        "removed": "تمت الإزالة",
        "source": "المصدر: البنك المركزي الأوروبي (Frankfurter)",
        "source2": "المصدر: CoinGecko",
        "invalidinput": "قيمة غير صالحة",
        "radiation": "إشعاع",
        "light": "إضاءة",
        "language": "لغة",
        "data": "بيانات",
        "copied": "تم النسخ",
        "unitOnCopy": "الوحدة عند النسخ",
        "unitOnCopyInfo": "عرض الوحدة مع القيمة المنسوخة: 120 كم/س",

        "unit_speed": "السرعة",
        "unit_weight": "الوزن",
        "unit_length": "الطول",
        "unit_time": "الوقت",
        "unit_temperature": "درجة الحرارة",
        "unit_volume": "الحجم",
        "unit_shoe_size": "مقاس الحذاء",
        "unit_data_size": "حجم البيانات",
        "unit_data_transfer_speed": "سرعة نقل البيانات",
        "unit_pressure": "الضغط",
        "unit_power": "الطاقة",
        "unit_torque": "العزم",
        "unit_currency": "العملة",
        "unit_area": "المساحة",
        "unit_crypto_beta": "العملات الرقمية (beta)",
        "unit_energy": "الطاقة",
        "unit_shares": "نسبة / تناسب",
        "unit_viscosity_dynamic": "اللزوجة (ديناميكية)",
        "unit_viscosity_kinematic": "اللزوجة (حركية)",
        "unit_angles": "الزوايا",
        "unit_electric_current": "التيار الكهربائي",
        "unit_electric_resistance": "المقاومة الكهربائية",
        "unit_numeral_system": "نظام الأرقام",
        "unit_magnetomotive_force": "القوة الدافعة المغناطيسية",
        "unit_magnetic_field_strength": "شدة المجال المغناطيسي",
        "unit_magnetic_flux": "التدفق المغناطيسي",
        "unit_image_resolution": "دقة الصورة",
        "unit_inductance": "الحث",
        "unit_charge": "الشحنة",
        "unit_linear_charge": "كثافة الشحنة الخطية",
        "unit_volume_charge": "كثافة الشحنة الحجمية",
        "unit_surface_charge": "كثافة الشحنة السطحية",
        "unit_magnetic_flux_density": "كثافة التدفق المغناطيسي",
        "unit_radiation": "إشعاع",
        "unit_radiation_activity": "نشاط الإشعاع",
        "unit_radiation_exposure": "التعرض للإشعاع",
        "unit_radiation_absorbed": "الإشعاع – الجرعة الممتصة",
        "unit_linear_current": "كثافة التيار الخطي",
        "unit_surface_tension": "التوتر السطحي",
        "unit_flow_rate": "معدل التدفق",
        "unit_concentration_solution": "التركيز (محلول)",
        "unit_mass_flux_density": "كثافة تدفق الكتلة",
        "unit_luminance": "السطوع",
        "unit_luminous_intensity": "شدة الإضاءة",
        "unit_luminous_flux": "التدفق الضوئي",
        "unit_illuminance": "الاستضاءة",
        "unit_frequency": "التردد",
        "unit_fuel_consumption": "استهلاك الوقود",
    ]

    private let ru: [String: String] = [ // Ryska
        "settings": "Настройки",
        "otherapps": "Другие приложения",
        "univertfeedback": "Обратная связь Univert",
        "givefeedback": "Оставить отзыв",
        "checkoutunivert": "Оцените приложение Univert!",
        "sharetheapp": "Поделиться приложением",
        "ratetheapp": "Оценить приложение",
        "about": "О приложении",
        "processing...": "Обработка...",
        "purchasecouldntrestore": "Не удалось восстановить покупки",
        "restorefailed": "Восстановление не удалось",
        "purchaserestored": "Ваша покупка восстановлена",
        "restorepurchase": "Восстановить покупку",
        "advancedunitsunlocked": "Расширенные единицы разблокированы",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Расширенные единицы",
        "cancel": "Отмена",
        "favoritescleared": "Избранное очищено",
        "clear": "Очистить",
        "clearfavorites?": "Вы хотите очистить сохраненные избранные?",
        "clearfavorites": "Очистить избранное",
        "favorites": "Избранное",
        "comma": "Запятая как десятичный разделитель",
        "darkmode": "Темный режим",
        "appearance": "Внешний вид",
        "notaddedfavorites": "Вы еще не добавили избранное",
        "purchasefailed": "Покупка не удалась, пожалуйста, попробуйте еще раз",
        "thanksforpurchase": "Спасибо за покупку!",
        "loading...": "Загрузка...",
        "getaccess": "Получите доступ ко всем расширенным единицам с помощью разовой покупки",
        "fluid": "Жидкость",
        "electricity": "Электричество",
        "magnetism": "Магнетизм",
        "monetaryunits": "Денежные единицы",
        "commonunits": "Общие единицы",
        "searchunits": "Поиск единиц",
        "units": "Единицы",
        "from": "Из",
        "to": "в",
        "value": "Значение",
        "speed": "Скорость",
        "addedtofavorites": "Добавлено в избранное",
        "removed": "Удалено",
        "source": "Источник: Европейский Центральный Банк (Frankfurter)",
        "source2": "Источник: CoinGecko",
        "invalidinput": "Недопустимое значение",
        "radiation": "Излучение",
        "light": "Освещение",
        "language": "Язык",
        "data": "Данные",
        "copied": "Скопировано",
        "unitOnCopy": "Единица при копировании",
        "unitOnCopyInfo": "Показать единицу вместе со скопированным значением: 120 km/h",
        
        "unit_speed": "Скорость",
        "unit_weight": "Вес",
        "unit_length": "Длина",
        "unit_time": "Время",
        "unit_temperature": "Температура",
        "unit_volume": "Объем",
        "unit_shoe_size": "Размер обуви",
        "unit_data_size": "Размер данных",
        "unit_data_transfer_speed": "Скорость передачи данных",
        "unit_pressure": "Давление",
        "unit_power": "Мощность",
        "unit_torque": "Крутящий момент",
        "unit_currency": "Валюта",
        "unit_area": "Площадь",
        "unit_crypto_beta": "Криптовалюта (бета)",
        "unit_energy": "Энергия",
        "unit_shares": "Соотношение / Пропорция",
        "unit_viscosity_dynamic": "Вязкость (динамическая)",
        "unit_viscosity_kinematic": "Вязкость (кинематическая)",
        "unit_angles": "Углы",
        "unit_electric_current": "Электрический ток",
        "unit_electric_resistance": "Электрическое сопротивление",
        "unit_numeral_system": "Система счисления",
        "unit_magnetomotive_force": "Магнитодвижущая сила",
        "unit_magnetic_field_strength": "Напряженность магнитного поля",
        "unit_magnetic_flux": "Магнитный поток",
        "unit_image_resolution": "Разрешение изображения",
        "unit_inductance": "Индуктивность",
        "unit_charge": "Заряд",
        "unit_linear_charge": "Линейная плотность заряда",
        "unit_volume_charge": "Объемная плотность заряда",
        "unit_surface_charge": "Поверхностная плотность заряда",
        "unit_magnetic_flux_density": "Плотность магнитного потока",
        "unit_radiation": "Радиация",
        "unit_radiation_activity": "Радиоактивность",
        "unit_radiation_exposure": "Радиационное облучение",
        "unit_radiation_absorbed": "Радиация – Поглощенная доза",
        "unit_linear_current": "Линейная плотность тока",
        "unit_surface_tension": "Поверхностное натяжение",
        "unit_flow_rate": "Скорость потока",
        "unit_concentration_solution": "Концентрация (раствор)",
        "unit_mass_flux_density": "Плотность массового потока",
        "unit_luminance": "Яркость",
        "unit_luminous_intensity": "Сила света",
        "unit_luminous_flux": "Световой поток",
        "unit_illuminance": "Освещенность",
        "unit_frequency": "Частота",
        "unit_fuel_consumption": "Расход топлива",
    ]

    private let ja: [String: String] = [ // Japanska
        "settings": "設定",
        "otherapps": "他のアプリ",
        "univertfeedback": "Univert フィードバック",
        "givefeedback": "フィードバックを送る",
        "checkoutunivert": "Univert アプリをチェック！",
        "sharetheapp": "アプリを共有",
        "ratetheapp": "アプリを評価",
        "about": "について",
        "processing...": "処理中...",
        "purchasecouldntrestore": "購入を復元できませんでした",
        "restorefailed": "復元に失敗しました",
        "purchaserestored": "購入が復元されました",
        "restorepurchase": "購入を復元",
        "advancedunitsunlocked": "高度な単位がロック解除されました",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "高度な単位",
        "cancel": "キャンセル",
        "favoritescleared": "お気に入りをクリアしました",
        "clear": "クリア",
        "clearfavorites?": "保存したお気に入りをクリアしますか？",
        "clearfavorites": "お気に入りをクリア",
        "favorites": "お気に入り",
        "comma": "小数点区切り記号のカンマ",
        "darkmode": "ダークモード",
        "appearance": "外観",
        "notaddedfavorites": "まだお気に入りを追加していません",
        "purchasefailed": "購入に失敗しました。もう一度お試しください",
        "thanksforpurchase": "ご購入いただきありがとうございます！",
        "loading...": "読み込み中...",
        "getaccess": "一度の購入ですべての高度な単位にアクセス",
        "fluid": "流体",
        "electricity": "電気",
        "magnetism": "磁気",
        "monetaryunits": "通貨単位",
        "commonunits": "一般単位",
        "searchunits": "単位を検索",
        "units": "単位",
        "from": "から",
        "to": "へ",
        "value": "値",
        "speed": "速度",
        "addedtofavorites": "お気に入りに追加しました",
        "removed": "削除しました",
        "source": "出典：欧州中央銀行（Frankfurter）",
        "source2": "出典：CoinGecko",
        "invalidinput": "無効な値",
        "radiation": "放射線",
        "light": "照明",
        "language": "言語",
        "data": "データ",
        "copied": "コピー済み",
        "unitOnCopy": "コピー時の単位",
        "unitOnCopyInfo": "コピーした値に単位を表示：120 km/h",

        "unit_speed": "速度",
        "unit_weight": "重さ",
        "unit_length": "長さ",
        "unit_time": "時間",
        "unit_temperature": "温度",
        "unit_volume": "体積",
        "unit_shoe_size": "靴のサイズ",
        "unit_data_size": "データサイズ",
        "unit_data_transfer_speed": "データ転送速度",
        "unit_pressure": "圧力",
        "unit_power": "パワー",
        "unit_torque": "トルク",
        "unit_currency": "通貨",
        "unit_area": "面積",
        "unit_crypto_beta": "仮想通貨（beta）",
        "unit_energy": "エネルギー",
        "unit_shares": "比率 / 割合",
        "unit_viscosity_dynamic": "粘度（動的）",
        "unit_viscosity_kinematic": "粘度（動粘度）",
        "unit_angles": "角度",
        "unit_electric_current": "電流",
        "unit_electric_resistance": "電気抵抗",
        "unit_numeral_system": "数値システム",
        "unit_magnetomotive_force": "起磁力",
        "unit_magnetic_field_strength": "磁場強度",
        "unit_magnetic_flux": "磁束",
        "unit_image_resolution": "画像解像度",
        "unit_inductance": "インダクタンス",
        "unit_charge": "電荷",
        "unit_linear_charge": "線電荷密度",
        "unit_volume_charge": "体積電荷密度",
        "unit_surface_charge": "表面電荷密度",
        "unit_magnetic_flux_density": "磁束密度",
        "unit_radiation": "放射線",
        "unit_radiation_activity": "放射能",
        "unit_radiation_exposure": "放射線被ばく",
        "unit_radiation_absorbed": "放射線 – 吸収線量",
        "unit_linear_current": "線電流密度",
        "unit_surface_tension": "表面張力",
        "unit_flow_rate": "流量",
        "unit_concentration_solution": "濃度（溶液）",
        "unit_mass_flux_density": "質量フラックス密度",
        "unit_luminance": "輝度",
        "unit_luminous_intensity": "光度",
        "unit_luminous_flux": "光束",
        "unit_illuminance": "照度",
        "unit_frequency": "周波数",
        "unit_fuel_consumption": "燃料消費量",
    ]

    private let it: [String: String] = [ // Italienska
        "settings": "Impostazioni",
        "otherapps": "Altre app",
        "univertfeedback": "Feedback Univert",
        "givefeedback": "Invia feedback",
        "checkoutunivert": "Scopri l'app Univert!",
        "sharetheapp": "Condividi l'app",
        "ratetheapp": "Valuta l'app",
        "about": "Informazioni",
        "processing...": "Elaborazione...",
        "purchasecouldntrestore": "Nessun acquisto ripristinabile",
        "restorefailed": "Ripristino fallito",
        "purchaserestored": "Il tuo acquisto è stato ripristinato",
        "restorepurchase": "Ripristina acquisto",
        "advancedunitsunlocked": "Unità avanzate sbloccate",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Unità avanzate",
        "cancel": "Annulla",
        "favoritescleared": "Preferiti cancellati",
        "clear": "Cancella",
        "clearfavorites?": "Vuoi cancellare i tuoi preferiti salvati?",
        "clearfavorites": "Cancella preferiti",
        "favorites": "Preferiti",
        "comma": "Separatore decimale virgola",
        "darkmode": "Modalità scura",
        "appearance": "Aspetto",
        "notaddedfavorites": "Non hai ancora aggiunto nessun preferito",
        "purchasefailed": "Acquisto fallito, riprova",
        "thanksforpurchase": "Grazie per l'acquisto!",
        "loading...": "Caricamento...",
        "getaccess": "Ottieni accesso a tutte le unità avanzate con un acquisto una tantum",
        "fluid": "Fluido",
        "electricity": "Elettricità",
        "magnetism": "Magnetismo",
        "monetaryunits": "Unità monetarie",
        "commonunits": "Unità comuni",
        "searchunits": "Cerca unità",
        "units": "Unità",
        "from": "Da",
        "to": "a",
        "value": "Valore",
        "speed": "Velocità",
        "addedtofavorites": "Aggiunto ai preferiti",
        "removed": "Rimosso",
        "source": "Fonte: Banca Centrale Europea (Frankfurter)",
        "source2": "Fonte: CoinGecko",
        "invalidinput": "Valore non valido",
        "radiation": "Radiazione",
        "light": "Illuminazione",
        "language": "Lingua",
        "data": "Dati",
        "copied": "Copiato",
        "unitOnCopy": "Unità durante la copia",
        "unitOnCopyInfo": "Mostra l'unità con il valore copiato: 120 km/h",

        "unit_speed": "Velocità",
        "unit_weight": "Peso",
        "unit_length": "Lunghezza",
        "unit_time": "Tempo",
        "unit_temperature": "Temperatura",
        "unit_volume": "Volume",
        "unit_shoe_size": "Numero di scarpa",
        "unit_data_size": "Dimensione dati",
        "unit_data_transfer_speed": "Velocità di trasferimento dati",
        "unit_pressure": "Pressione",
        "unit_power": "Potenza",
        "unit_torque": "Coppia",
        "unit_currency": "Valuta",
        "unit_area": "Area",
        "unit_crypto_beta": "Cripto (beta)",
        "unit_energy": "Energia",
        "unit_shares": "Rapporto / Proporzione",
        "unit_viscosity_dynamic": "Viscosità (dinamica)",
        "unit_viscosity_kinematic": "Viscosità (cinematica)",
        "unit_angles": "Angoli",
        "unit_electric_current": "Corrente elettrica",
        "unit_electric_resistance": "Resistenza elettrica",
        "unit_numeral_system": "Sistema numerico",
        "unit_magnetomotive_force": "Forza magnetomotrice",
        "unit_magnetic_field_strength": "Intensità del campo magnetico",
        "unit_magnetic_flux": "Flusso magnetico",
        "unit_image_resolution": "Risoluzione dell'immagine",
        "unit_inductance": "Induttanza",
        "unit_charge": "Carica",
        "unit_linear_charge": "Densità di carica lineare",
        "unit_volume_charge": "Densità di carica volumetrica",
        "unit_surface_charge": "Densità di carica superficiale",
        "unit_magnetic_flux_density": "Densità del flusso magnetico",
        "unit_radiation": "Radiazione",
        "unit_radiation_activity": "Attività di radiazione",
        "unit_radiation_exposure": "Esposizione alle radiazioni",
        "unit_radiation_absorbed": "Radiazione – Dose assorbita",
        "unit_linear_current": "Densità di corrente lineare",
        "unit_surface_tension": "Tensione superficiale",
        "unit_flow_rate": "Portata",
        "unit_concentration_solution": "Concentrazione (soluzione)",
        "unit_mass_flux_density": "Densità di flusso di massa",
        "unit_luminance": "Luminanza",
        "unit_luminous_intensity": "Intensità luminosa",
        "unit_luminous_flux": "Flusso luminoso",
        "unit_illuminance": "Illuminamento",
        "unit_frequency": "Frequenza",
        "unit_fuel_consumption": "Consumo di carburante",
    ]

    private let tr: [String: String] = [ // Turkiska
        "settings": "Ayarlar",
        "otherapps": "Diğer uygulamalar",
        "univertfeedback": "Univert geri bildirimi",
        "givefeedback": "Geri bildirim ver",
        "checkoutunivert": "Univert uygulamasını incele!",
        "sharetheapp": "Uygulamayı paylaş",
        "ratetheapp": "Uygulamayı derecelendir",
        "about": "Hakkında",
        "processing...": "İşleniyor...",
        "purchasecouldntrestore": "Hiçbir satın alma geri yüklenemedi",
        "restorefailed": "Geri yükleme başarısız oldu",
        "purchaserestored": "Satın alma işleminiz geri yüklendi",
        "restorepurchase": "Satın almayı geri yükle",
        "advancedunitsunlocked": "Gelişmiş birimler kilidi açıldı",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Gelişmiş birimler",
        "cancel": "İptal",
        "favoritescleared": "Favoriler temizlendi",
        "clear": "Temizle",
        "clearfavorites?": "Kaydedilen favorilerinizi temizlemek ister misiniz?",
        "clearfavorites": "Favorileri temizle",
        "comma": "Ondalık ayırıcı virgül",
        "darkmode": "Koyu mod",
        "appearance": "Görünüm",
        "notaddedfavorites": "Henüz favori eklemediniz",
        "purchasefailed": "Satın alma başarısız oldu, lütfen tekrar deneyin",
        "thanksforpurchase": "Satın aldığınız için teşekkürler!",
        "loading...": "Yükleniyor...",
        "getaccess": "Tek seferlik bir satın alma ile tüm gelişmiş birimlere erişim sağlayın",
        "fluid": "Akışkan",
        "electricity": "Elektrik",
        "magnetism": "Manyetizma",
        "monetaryunits": "Para birimleri",
        "commonunits": "Ortak birimler",
        "searchunits": "Birimleri ara",
        "units": "Birimler",
        "from": "Şuradan",
        "to": "şuraya",
        "value": "Değer",
        "speed": "Hız",
        "addedtofavorites": "Favorilere eklendi",
        "removed": "Kaldırıldı",
        "source": "Kaynak: Avrupa Merkez Bankası (Frankfurter)",
        "source2": "Kaynak: CoinGecko",
        "invalidinput": "Geçersiz değer",
        "radiation": "Radyasyon",
        "light": "Aydınlatma",
        "language": "Dil",
        "data": "Veri",
        "copied": "Kopyalandı",
        "unitOnCopy": "Kopyalama sırasında birim",
        "unitOnCopyInfo": "Kopyalanan değerle birlikte birimi göster: 120 km/h",

        "unit_speed": "Hız",
        "unit_weight": "Ağırlık",
        "unit_length": "Uzunluk",
        "unit_time": "Zaman",
        "unit_temperature": "Sıcaklık",
        "unit_volume": "Hacim",
        "unit_shoe_size": "Ayakkabı numarası",
        "unit_data_size": "Veri boyutu",
        "unit_data_transfer_speed": "Veri Aktarım Hızı",
        "unit_pressure": "Basınç",
        "unit_power": "Güç",
        "unit_torque": "Tork",
        "unit_currency": "Para Birimi",
        "unit_area": "Alan",
        "unit_crypto_beta": "Kripto (beta)",
        "unit_energy": "Enerji",
        "unit_shares": "Oran / Orantı",
        "unit_viscosity_dynamic": "Viskozite (dinamik)",
        "unit_viscosity_kinematic": "Viskozite (kinematik)",
        "unit_angles": "Açılar",
        "unit_electric_current": "Elektrik Akımı",
        "unit_electric_resistance": "Elektrik Direnci",
        "unit_numeral_system": "Sayı Sistemi",
        "unit_magnetomotive_force": "Manyetomotor Kuvvet",
        "unit_magnetic_field_strength": "Manyetik Alan Şiddeti",
        "unit_magnetic_flux": "Manyetik Akı",
        "unit_image_resolution": "Görüntü Çözünürlüğü",
        "unit_inductance": "İndüktans",
        "unit_charge": "Şarj",
        "unit_linear_charge": "Doğrusal Şarj Yoğunluğu",
        "unit_volume_charge": "Hacim Şarj Yoğunluğu",
        "unit_surface_charge": "Yüzey Şarj Yoğunluğu",
        "unit_magnetic_flux_density": "Manyetik Akı Yoğunluğu",
        "unit_radiation": "Radyasyon",
        "unit_radiation_activity": "Radyasyon Aktivitesi",
        "unit_radiation_exposure": "Radyasyona Maruz Kalma",
        "unit_radiation_absorbed": "Radyasyon – Emilmiş Doz",
        "unit_linear_current": "Doğrusal Akım Yoğunluğu",
        "unit_surface_tension": "Yüzey Gerilimi",
        "unit_flow_rate": "Akış Hızı",
        "unit_concentration_solution": "Konsantrasyon (çözelti)",
        "unit_mass_flux_density": "Kütle Akı Yoğunluğu",
        "unit_luminance": "Parlaklık",
        "unit_luminous_intensity": "Işık Şiddeti",
        "unit_luminous_flux": "Işık Akısı",
        "unit_illuminance": "Aydınlatma",
        "unit_frequency": "Frekans",
        "unit_fuel_consumption": "Yakıt Tüketimi",
    ]

    private let ko: [String: String] = [ // Koreanska
        "settings": "설정",
        "otherapps": "다른 앱",
        "univertfeedback": "Univert 피드백",
        "givefeedback": "피드백 보내기",
        "checkoutunivert": "Univert 앱을 확인해보세요!",
        "sharetheapp": "앱 공유하기",
        "ratetheapp": "앱 평가하기",
        "about": "정보",
        "processing...": "처리 중...",
        "purchasecouldntrestore": "구매를 복원할 수 없습니다",
        "restorefailed": "복원 실패",
        "purchaserestored": "구매가 복원되었습니다",
        "restorepurchase": "구매 복원",
        "advancedunitsunlocked": "고급 단위 잠금 해제됨",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "고급 단위",
        "cancel": "취소",
        "favoritescleared": "즐겨찾기 지워짐",
        "clear": "지우기",
        "clearfavorites?": "저장된 즐겨찾기를 지우시겠습니까?",
        "clearfavorites": "즐겨찾기 지우기",
        "favorites": "즐겨찾기",
        "comma": "쉼표 소수 구분 기호",
        "darkmode": "다크 모드",
        "appearance": "외관",
        "notaddedfavorites": "아직 즐겨찾기를 추가하지 않았습니다",
        "purchasefailed": "구매 실패, 다시 시도해 주세요",
        "thanksforpurchase": "구매해 주셔서 감사합니다!",
        "loading...": "로딩 중...",
        "getaccess": "일회성 구매로 모든 고급 단위를 이용하세요",
        "fluid": "유체",
        "electricity": "전기",
        "magnetism": "자기",
        "monetaryunits": "화폐 단위",
        "commonunits": "일반 단위",
        "searchunits": "단위 검색",
        "units": "단위",
        "from": "에서",
        "to": "으로",
        "value": "값",
        "speed": "속도",
        "addedtofavorites": "즐겨찾기에 추가됨",
        "removed": "제거됨",
        "source": "출처: 유럽 중앙은행 (Frankfurter)",
        "source2": "출처: CoinGecko",
        "invalidinput": "유효하지 않은 값",
        "radiation": "방사선",
        "light": "조명",
        "language": "언어",
        "data": "데이터",
        "copied": "복사됨",
        "unitOnCopy": "복사 시 단위 포함",
        "unitOnCopyInfo": "복사된 값에 단위를 표시: 120 km/h",

        "unit_speed": "속도",
        "unit_weight": "무게",
        "unit_length": "길이",
        "unit_time": "시간",
        "unit_temperature": "온도",
        "unit_volume": "부피",
        "unit_shoe_size": "신발 사이즈",
        "unit_data_size": "데이터 크기",
        "unit_data_transfer_speed": "데이터 전송 속도",
        "unit_pressure": "압력",
        "unit_power": "전력",
        "unit_torque": "토크",
        "unit_currency": "통화",
        "unit_area": "면적",
        "unit_crypto_beta": "암호화폐 (beta)",
        "unit_energy": "에너지",
        "unit_shares": "비율 / 비례",
        "unit_viscosity_dynamic": "점도 (동적)",
        "unit_viscosity_kinematic": "점도 (동점도)",
        "unit_angles": "각도",
        "unit_electric_current": "전류",
        "unit_electric_resistance": "전기 저항",
        "unit_numeral_system": "숫자 체계",
        "unit_magnetomotive_force": "자기 기전력",
        "unit_magnetic_field_strength": "자기장 세기",
        "unit_magnetic_flux": "자속",
        "unit_image_resolution": "이미지 해상도",
        "unit_inductance": "인덕턴스",
        "unit_charge": "전하",
        "unit_linear_charge": "선 전하 밀도",
        "unit_volume_charge": "부피 전하 밀도",
        "unit_surface_charge": "표면 전하 밀도",
        "unit_magnetic_flux_density": "자속 밀도",
        "unit_radiation": "방사선",
        "unit_radiation_activity": "방사능",
        "unit_radiation_exposure": "방사선 노출",
        "unit_radiation_absorbed": "방사선 – 흡수선량",
        "unit_linear_current": "선 전류 밀도",
        "unit_surface_tension": "표면 장력",
        "unit_flow_rate": "유량",
        "unit_concentration_solution": "농도 (용액)",
        "unit_mass_flux_density": "질량 유량 밀도",
        "unit_luminance": "휘도",
        "unit_luminous_intensity": "광도",
        "unit_luminous_flux": "광선속",
        "unit_illuminance": "조도",
        "unit_frequency": "주파수",
        "unit_fuel_consumption": "연료 소비량",
    ]

    private let pl: [String: String] = [ // Polska
        "settings": "Ustawienia",
        "otherapps": "Inne aplikacje",
        "univertfeedback": "Opinie Univert",
        "givefeedback": "Wyślij opinię",
        "checkoutunivert": "Sprawdź aplikację Univert!",
        "sharetheapp": "Udostępnij aplikację",
        "ratetheapp": "Oceń aplikację",
        "about": "O aplikacji",
        "processing...": "Przetwarzanie...",
        "purchasecouldntrestore": "Nie można przywrócić zakupów",
        "restorefailed": "Przywracanie nie powiodło się",
        "purchaserestored": "Twój zakup został przywrócony",
        "restorepurchase": "Przywróć zakup",
        "advancedunitsunlocked": "Zaawansowane jednostki odblokowane",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Zaawansowane jednostki",
        "cancel": "Anuluj",
        "favoritescleared": "Ulubione wyczyszczone",
        "clear": "Wyczyść",
        "clearfavorites?": "Czy chcesz wyczyścić zapisane ulubione?",
        "clearfavorites": "Wyczyść ulubione",
        "favorites": "Ulubione",
        "comma": "Przecinek jako separator dziesiętny",
        "darkmode": "Tryb ciemny",
        "appearance": "Wygląd",
        "notaddedfavorites": "Nie dodałeś jeszcze żadnych ulubionych",
        "purchasefailed": "Zakup nie powiódł się, spróbuj ponownie",
        "thanksforpurchase": "Dziękujemy za zakup!",
        "loading...": "Ładowanie...",
        "getaccess": "Uzyskaj dostęp do wszystkich zaawansowanych jednostek dzięki jednorazowemu zakupowi",
        "fluid": "Płyn",
        "electricity": "Elektryczność",
        "magnetism": "Magnetyzm",
        "monetaryunits": "Jednostki monetarne",
        "commonunits": "Popularne jednostki",
        "searchunits": "Szukaj jednostek",
        "units": "Jednostki",
        "from": "Z",
        "to": "do",
        "value": "Wartość",
        "speed": "Prędkość",
        "addedtofavorites": "Dodano do ulubionych",
        "removed": "Usunięto",
        "source": "Źródło: Europejski Bank Centralny (Frankfurter)",
        "source2": "Źródło: CoinGecko",
        "invalidinput": "Nieprawidłowa wartość",
        "radiation": "Promieniowanie",
        "light": "Oświetlenie",
        "language": "Język",
        "data": "Dane",
        "copied": "Skopiowano",
        "unitOnCopy": "Jednostka przy kopiowaniu",
        "unitOnCopyInfo": "Pokaż jednostkę wraz ze skopiowaną wartością: 120 km/h",
        
        "unit_speed": "Prędkość",
        "unit_weight": "Waga",
        "unit_length": "Długość",
        "unit_time": "Czas",
        "unit_temperature": "Temperatura",
        "unit_volume": "Objętość",
        "unit_shoe_size": "Rozmiar buta",
        "unit_data_size": "Rozmiar danych",
        "unit_data_transfer_speed": "Prędkość transferu danych",
        "unit_pressure": "Ciśnienie",
        "unit_power": "Moc",
        "unit_torque": "Moment obrotowy",
        "unit_currency": "Waluta",
        "unit_area": "Powierzchnia",
        "unit_crypto_beta": "Krypto (beta)",
        "unit_energy": "Energia",
        "unit_shares": "Współczynnik / Proporcja",
        "unit_viscosity_dynamic": "Lepkość (dynamiczna)",
        "unit_viscosity_kinematic": "Lepkość (kinematyczna)",
        "unit_angles": "Kąty",
        "unit_electric_current": "Prąd elektryczny",
        "unit_electric_resistance": "Opór elektryczny",
        "unit_numeral_system": "System liczbowy",
        "unit_magnetomotive_force": "Siła magnetomotoryczna",
        "unit_magnetic_field_strength": "Natężenie pola magnetycznego",
        "unit_magnetic_flux": "Strumień magnetyczny",
        "unit_image_resolution": "Rozdzielczość obrazu",
        "unit_inductance": "Indukcyjność",
        "unit_charge": "Ładunek",
        "unit_linear_charge": "Liniowa gęstość ładunku",
        "unit_volume_charge": "Objętościowa gęstość ładunku",
        "unit_surface_charge": "Powierzchniowa gęstość ładunku",
        "unit_magnetic_flux_density": "Gęstość strumienia magnetycznego",
        "unit_radiation": "Promieniowanie",
        "unit_radiation_activity": "Aktywność promieniowania",
        "unit_radiation_exposure": "Ekspozycja na promieniowanie",
        "unit_radiation_absorbed": "Promieniowanie – Dawka pochłonięta",
        "unit_linear_current": "Liniowa gęstość prądu",
        "unit_surface_tension": "Napięcie powierzchniowe",
        "unit_flow_rate": "Natężenie przepływu",
        "unit_concentration_solution": "Stężenie (roztwór)",
        "unit_mass_flux_density": "Gęstość strumienia masy",
        "unit_luminance": "Luminancja",
        "unit_luminous_intensity": "Światłość",
        "unit_luminous_flux": "Strumień świetlny",
        "unit_illuminance": "Natężenie oświetlenia",
        "unit_frequency": "Częstotliwość",
        "unit_fuel_consumption": "Zużycie paliwa",
    ]

    private let el: [String: String] = [ // Grekiska
        "settings": "Ρυθμίσεις",
        "otherapps": "Άλλες εφαρμογές",
        "univertfeedback": "Σχόλια Univert",
        "givefeedback": "Δώστε σχόλια",
        "checkoutunivert": "Δείτε την εφαρμογή Univert!",
        "sharetheapp": "Κοινοποιήστε την εφαρμογή",
        "ratetheapp": "Βαθμολογήστε την εφαρμογή",
        "about": "Σχετικά",
        "processing...": "Επεξεργασία...",
        "purchasecouldntrestore": "Δεν ήταν δυνατή η επαναφορά αγορών",
        "restorefailed": "Η επαναφορά απέτυχε",
        "purchaserestored": "Η αγορά σας έχει αποκατασταθεί",
        "restorepurchase": "Επαναφορά αγοράς",
        "advancedunitsunlocked": "Προηγμένες μονάδες ξεκλείδωτες",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Προηγμένες μονάδες",
        "cancel": "Ακύρωση",
        "favoritescleared": "Τα αγαπημένα εκκαθαρίστηκαν",
        "clear": "Εκκαθάριση",
        "clearfavorites?": "Θέλετε να εκκαθαρίσετε τα αποθηκευμένα αγαπημένα σας;",
        "clearfavorites": "Εκκαθάριση αγαπημένων",
        "favorites": "Αγαπημένα",
        "comma": "Διαχωριστικό δεκαδικών κόμμα",
        "darkmode": "Σκοτεινή λειτουργία",
        "appearance": "Εμφάνιση",
        "notaddedfavorites": "Δεν έχετε προσθέσει ακόμη αγαπημένα",
        "purchasefailed": "Η αγορά απέτυχε, παρακαλώ προσπαθήστε ξανά",
        "thanksforpurchase": "Ευχαριστούμε για την αγορά σας!",
        "loading...": "Φορτώνει...",
        "getaccess": "Αποκτήστε πρόσβαση σε όλες τις προηγμένες μονάδες με μία εφάπαξ αγορά",
        "fluid": "Ρευστό",
        "electricity": "Ηλεκτρισμός",
        "magnetism": "Μαγνητισμός",
        "monetaryunits": "Νομισματικές μονάδες",
        "commonunits": "Κοινές μονάδες",
        "searchunits": "Αναζήτηση μονάδων",
        "units": "Μονάδες",
        "from": "Από",
        "to": "προς",
        "value": "Αξία",
        "speed": "Ταχύτητα",
        "addedtofavorites": "Προστέθηκε στα αγαπημένα",
        "removed": "Αφαιρέθηκε",
        "source": "Πηγή: Ευρωπαϊκή Κεντρική Τράπεζα (Frankfurter)",
        "source2": "Πηγή: CoinGecko",
        "invalidinput": "Μη έγκυρη τιμή",
        "radiation": "Ακτινοβολία",
        "light": "Φωτισμός",
        "language": "Γλώσσα",
        "data": "Δεδομένα",
        "copied": "Αντιγράφηκε",
        "unitOnCopy": "Μονάδα κατά την αντιγραφή",
        "unitOnCopyInfo": "Εμφάνιση μονάδας με την αντιγραμμένη τιμή: 120 km/h",

        "unit_speed": "Ταχύτητα",
        "unit_weight": "Βάρος",
        "unit_length": "Μήκος",
        "unit_time": "Ώρα",
        "unit_temperature": "Θερμοκρασία",
        "unit_volume": "Όγκος",
        "unit_shoe_size": "Μέγεθος παπουτσιού",
        "unit_data_size": "Μέγεθος δεδομένων",
        "unit_data_transfer_speed": "Ταχύτητα μεταφοράς δεδομένων",
        "unit_pressure": "Πίεση",
        "unit_power": "Ισχύς",
        "unit_torque": "Ροπή",
        "unit_currency": "Νόμισμα",
        "unit_area": "Εμβαδόν",
        "unit_crypto_beta": "Κρυπτογράφηση (beta)",
        "unit_energy": "Ενέργεια",
        "unit_shares": "Αναλογία / Ποσοστό",
        "unit_viscosity_dynamic": "Ιξώδες (δυναμικό)",
        "unit_viscosity_kinematic": "Ιξώδες (κινηματικό)",
        "unit_angles": "Γωνίες",
        "unit_electric_current": "Ηλεκτρικό ρεύμα",
        "unit_electric_resistance": "Ηλεκτρική αντίσταση",
        "unit_numeral_system": "Αριθμητικό σύστημα",
        "unit_magnetomotive_force": "Μαγνητοκινητική δύναμη",
        "unit_magnetic_field_strength": "Ένταση μαγνητικού πεδίου",
        "unit_magnetic_flux": "Μαγνητική ροή",
        "unit_image_resolution": "Ανάλυση εικόνας",
        "unit_inductance": "Επαγωγή",
        "unit_charge": "Φορτίο",
        "unit_linear_charge": "Γραμμική πυκνότητα φορτίου",
        "unit_volume_charge": "Πυκνότητα όγκου φορτίου",
        "unit_surface_charge": "Πυκνότητα επιφάνειας φορτίου",
        "unit_magnetic_flux_density": "Πυκνότητα μαγνητικής ροής",
        "unit_radiation": "Ακτινοβολία",
        "unit_radiation_activity": "Ραδιενεργός δραστηριότητα",
        "unit_radiation_exposure": "Έκθεση σε ακτινοβολία",
        "unit_radiation_absorbed": "Ακτινοβολία – Απορροφημένη δόση",
        "unit_linear_current": "Γραμμική πυκνότητα ρεύματος",
        "unit_surface_tension": "Επιφανειακή τάση",
        "unit_flow_rate": "Ρυθμός ροής",
        "unit_concentration_solution": "Συγκέντρωση (διάλυμα)",
        "unit_mass_flux_density": "Πυκνότητα ροής μάζας",
        "unit_luminance": "Λαμπρότητα",
        "unit_luminous_intensity": "Φωτεινή ένταση",
        "unit_luminous_flux": "Φωτεινή ροή",
        "unit_illuminance": "Φωτισμός",
        "unit_frequency": "Συχνότητα",
        "unit_fuel_consumption": "Κατανάλωση καυσίμου",
    ]
    
    private let pt: [String: String] = [ // Portugisiska
        "settings": "Configurações",
        "otherapps": "Outros aplicativos",
        "univertfeedback": "Feedback do Univert",
        "givefeedback": "Enviar feedback",
        "checkoutunivert": "Confira o aplicativo Univert!",
        "sharetheapp": "Compartilhar aplicativo",
        "ratetheapp": "Avaliar aplicativo",
        "about": "Sobre",
        "processing...": "Processando...",
        "purchasecouldntrestore": "Nenhuma compra pôde ser restaurada",
        "restorefailed": "Restauração falhou",
        "purchaserestored": "Sua compra foi restaurada",
        "restorepurchase": "Restaurar compra",
        "advancedunitsunlocked": "Unidades avançadas desbloqueadas",
        "unlockadvancedunits": "Univert PRO",
        "advancedunits": "Unidades avançadas",
        "cancel": "Cancelar",
        "favoritescleared": "Favoritos limpos",
        "clear": "Limpar",
        "clearfavorites?": "Deseja limpar seus favoritos salvos?",
        "clearfavorites": "Limpar favoritos",
        "favorites": "Favoritos",
        "comma": "Separador decimal de vírgula",
        "darkmode": "Modo escuro",
        "appearance": "Aparência",
        "notaddedfavorites": "Você ainda não adicionou nenhum favorito",
        "purchasefailed": "Compra falhou, tente novamente",
        "thanksforpurchase": "Obrigado pela sua compra!",
        "loading...": "Carregando...",
        "getaccess": "Obtenha acesso a todas as unidades avançadas com uma compra única",
        "fluid": "Fluido",
        "electricity": "Eletricidade",
        "magnetism": "Magnetismo",
        "monetaryunits": "Unidades monetárias",
        "commonunits": "Unidades comuns",
        "searchunits": "Pesquisar unidades",
        "units": "Unidades",
        "from": "De",
        "to": "para",
        "value": "Valor",
        "speed": "Velocidade",
        "addedtofavorites": "Adicionado aos favoritos",
        "removed": "Removido",
        "source": "Fonte: Banco Central Europeu (Frankfurter)",
        "source2": "Fonte: CoinGecko",
        "invalidinput": "Valor inválido",
        "radiation": "Radiação",
        "light": "Iluminação",
        "language": "Idioma",
        "data": "Dados",
        "copied": "Copiado",
        "unitOnCopy": "Unidade ao copiar",
        "unitOnCopyInfo": "Mostrar unidade com o valor copiado: 120 km/h",

        "unit_speed": "Velocidade",
        "unit_weight": "Peso",
        "unit_length": "Comprimento",
        "unit_time": "Tempo",
        "unit_temperature": "Temperatura",
        "unit_volume": "Volume",
        "unit_shoe_size": "Tamanho de Calçado",
        "unit_data_size": "Tamanho de Dados",
        "unit_data_transfer_speed": "Velocidade de Transferência de Dados",
        "unit_pressure": "Pressão",
        "unit_power": "Potência",
        "unit_torque": "Torque",
        "unit_currency": "Moeda",
        "unit_area": "Área",
        "unit_crypto_beta": "Cripto (beta)",
        "unit_energy": "Energia",
        "unit_shares": "Razão / Proporção",
        "unit_viscosity_dynamic": "Viscosidade (dinâmica)",
        "unit_viscosity_kinematic": "Viscosidade (cinemática)",
        "unit_angles": "Ângulos",
        "unit_electric_current": "Corrente Elétrica",
        "unit_electric_resistance": "Resistência Elétrica",
        "unit_numeral_system": "Sistema Numérico",
        "unit_magnetomotive_force": "Força Magnetomotriz",
        "unit_magnetic_field_strength": "Intensidade do Campo Magnético",
        "unit_magnetic_flux": "Fluxo Magnético",
        "unit_image_resolution": "Resolução de Imagem",
        "unit_inductance": "Indutância",
        "unit_charge": "Carga",
        "unit_linear_charge": "Densidade de Carga Linear",
        "unit_volume_charge": "Densidade de Carga Volumétrica",
        "unit_surface_charge": "Densidade de Carga Superficial",
        "unit_magnetic_flux_density": "Densidade de Fluxo Magnético",
        "unit_radiation": "Radiação",
        "unit_radiation_activity": "Atividade de Radiação",
        "unit_radiation_exposure": "Exposição à Radiação",
        "unit_radiation_absorbed": "Radiação – Dose Absorvida",
        "unit_linear_current": "Densidade de Corrente Linear",
        "unit_surface_tension": "Tensão Superficial",
        "unit_flow_rate": "Taxa de Fluxo",
        "unit_concentration_solution": "Concentração (solução)",
        "unit_mass_flux_density": "Densidade de Fluxo de Massa",
        "unit_luminance": "Luminância",
        "unit_luminous_intensity": "Intensidade Luminosa",
        "unit_luminous_flux": "Fluxo Luminoso",
        "unit_illuminance": "Iluminância",
        "unit_frequency": "Frequência",
        "unit_fuel_consumption": "Consumo de Combustível",
    ]

    private let hi: [String: String] = [ // Hindi
        "settings": "सेटिंग्स",
        "otherapps": "अन्य ऐप्स",
        "univertfeedback": "यूनिवर्ट फीडबैक",
        "givefeedback": "फीडबैक दें",
        "checkoutunivert": "यूनिवर्ट ऐप देखें!",
        "sharetheapp": "ऐप साझा करें",
        "ratetheapp": "ऐप को रेट करें",
        "about": "के बारे में",
        "processing...": "प्रसंस्करण हो रहा है...",
        "purchasecouldntrestore": "कोई खरीद बहाल नहीं की जा सकी",
        "restorefailed": "बहाली विफल रही",
        "purchaserestored": "आपकी खरीद बहाल कर दी गई है",
        "restorepurchase": "खरीद बहाल करें",
        "advancedunitsunlocked": "उन्नत इकाइयां अनलॉक की गईं",
        "unlockadvancedunits": "यूनिवर्ट प्रो",
        "advancedunits": "उन्नत इकाइयां",
        "cancel": "रद्द करें",
        "favoritescleared": "पसंदीदा हटा दिए गए",
        "clear": "साफ करें",
        "clearfavorites?": "क्या आप अपनी सहेजी गई पसंदीदा को साफ करना चाहते हैं?",
        "clearfavorites": "पसंदीदा साफ करें",
        "favorites": "पसंदीदा",
        "comma": "अल्पविराम दशमलव विभाजक",
        "darkmode": "डार्क मोड",
        "appearance": "दिखावट",
        "notaddedfavorites": "आपने अभी तक कोई पसंदीदा नहीं जोड़ा है",
        "purchasefailed": "खरीद विफल रही, कृपया पुनः प्रयास करें",
        "thanksforpurchase": "आपकी खरीद के लिए धन्यवाद!",
        "loading...": "लोड हो रहा है...",
        "getaccess": "एकमुश्त खरीद के साथ सभी उन्नत इकाइयों तक पहुंच प्राप्त करें",
        "fluid": "द्रव",
        "electricity": "बिजली",
        "magnetism": "चुंबकत्व",
        "monetaryunits": "मौद्रिक इकाइयां",
        "commonunits": "सामान्य इकाइयां",
        "searchunits": "इकाइयां खोजें",
        "units": "इकाइयां",
        "from": "से",
        "to": "तक",
        "value": "मूल्य",
        "speed": "गति",
        "addedtofavorites": "पसंदीदा में जोड़ा गया",
        "removed": "हटाया गया",
        "source": "स्रोत: यूरोपीय सेंट्रल बैंक (Frankfurter)",
        "source2": "स्रोत: कॉइनगेको",
        "invalidinput": "अमान्य मान",
        "radiation": "विकिरण",
        "light": "प्रकाश",
        "language": "भाषा",
        "data": "डेटा",
        "copied": "कॉपी किया गया",
        "unitOnCopy": "कॉपी करते समय इकाई",
        "unitOnCopyInfo": "कॉपी किए गए मान के साथ इकाई दिखाएं: 120 km/h",
        
        "unit_speed": "गति",
        "unit_weight": "वजन",
        "unit_length": "लंबाई",
        "unit_time": "समय",
        "unit_temperature": "तापमान",
        "unit_volume": "आयतन",
        "unit_shoe_size": "जूते का आकार",
        "unit_data_size": "डेटा आकार",
        "unit_data_transfer_speed": "डेटा स्थानांतरण गति",
        "unit_pressure": "दबाव",
        "unit_power": "शक्ति",
        "unit_torque": "टॉर्क",
        "unit_currency": "मुद्रा",
        "unit_area": "क्षेत्र",
        "unit_crypto_beta": "क्रिप्टो (beta)",
        "unit_energy": "ऊर्जा",
        "unit_shares": "अनुपात / समानुपात",
        "unit_viscosity_dynamic": "श्यानता (गतिशील)",
        "unit_viscosity_kinematic": "श्यानता (काइनेटिक)",
        "unit_angles": "कोण",
        "unit_electric_current": "विद्युत धारा",
        "unit_electric_resistance": "विद्युत प्रतिरोध",
        "unit_numeral_system": "संख्या प्रणाली",
        "unit_magnetomotive_force": "चुंबकीय प्रेरक बल",
        "unit_magnetic_field_strength": "चुंबकीय क्षेत्र की तीव्रता",
        "unit_magnetic_flux": "चुंबकीय प्रवाह",
        "unit_image_resolution": "छवि संकल्प",
        "unit_inductance": "प्रेरकत्व",
        "unit_charge": "चार्ज",
        "unit_linear_charge": "रेखीय चार्ज घनत्व",
        "unit_volume_charge": "आयतन चार्ज घनत्व",
        "unit_surface_charge": "सतह चार्ज घनत्व",
        "unit_magnetic_flux_density": "चुंबकीय प्रवाह घनत्व",
        "unit_radiation": "विकिरण",
        "unit_radiation_activity": "विकिरण गतिविधि",
        "unit_radiation_exposure": "विकिरण एक्सपोजर",
        "unit_radiation_absorbed": "विकिरण – अवशोषित खुराक",
        "unit_linear_current": "रेखीय धारा घनत्व",
        "unit_surface_tension": "पृष्ठ तनाव",
        "unit_flow_rate": "प्रवाह दर",
        "unit_concentration_solution": "सांद्रता (घोल)",
        "unit_mass_flux_density": "द्रव्यमान प्रवाह घनत्व",
        "unit_luminance": "चमक",
        "unit_luminous_intensity": "चमकदार तीव्रता",
        "unit_luminous_flux": "चमकदार प्रवाह",
        "unit_illuminance": "प्रदीप्ति",
        "unit_frequency": "आवृत्ति",
        "unit_fuel_consumption": "ईंधन की खपत",
        ]
    
    private let bn: [String: String] = [ // Bengali
        "settings": "সেটিংস",
        "otherapps": "অন্যান্য অ্যাপস",
        "univertfeedback": "ইউনিভার্ট প্রতিক্রিয়া",
        "givefeedback": "প্রতিক্রিয়া দিন",
        "checkoutunivert": "ইউনিভার্ট অ্যাপটি দেখুন!",
        "sharetheapp": "অ্যাপটি শেয়ার করুন",
        "ratetheapp": "অ্যাপটিকে রেট দিন",
        "about": "সম্পর্কে",
        "processing...": "প্রক্রিয়াকরণ চলছে...",
        "purchasecouldntrestore": "কোনো কেনাকাটা পুনরুদ্ধার করা যায়নি",
        "restorefailed": "পুনরুদ্ধার ব্যর্থ হয়েছে",
        "purchaserestored": "আপনার কেনাকাটা পুনরুদ্ধার করা হয়েছে",
        "restorepurchase": "কেনাকাটা পুনরুদ্ধার করুন",
        "advancedunitsunlocked": "উন্নত ইউনিট আনলক করা হয়েছে",
        "unlockadvancedunits": "ইউনিভার্ট প্রো",
        "advancedunits": "উন্নত ইউনিট",
        "cancel": "বাতিল করুন",
        "favoritescleared": "প্রিয় তালিকা সাফ করা হয়েছে",
        "clear": "সাফ করুন",
        "clearfavorites?": "আপনি কি আপনার সংরক্ষিত প্রিয়গুলি সাফ করতে চান?",
        "clearfavorites": "প্রিয় তালিকা সাফ করুন",
        "favorites": "প্রিয়",
        "comma": "কমা দশমিক বিভাজক",
        "darkmode": "ডার্ক মোড",
        "appearance": "চেহারা",
        "notaddedfavorites": "আপনি এখনও কোনো প্রিয় যোগ করেননি",
        "purchasefailed": "কেনাকাটা ব্যর্থ হয়েছে, আবার চেষ্টা করুন",
        "thanksforpurchase": "আপনার কেনার জন্য ধন্যবাদ!",
        "loading...": "লোড হচ্ছে...",
        "getaccess": "এককালীন কেনাকাটায় সকল উন্নত ইউনিটগুলিতে অ্যাক্সেস পান",
        "fluid": "তরল",
        "electricity": "বিদ্যুৎ",
        "magnetism": "চুম্বকত্ব",
        "monetaryunits": "মুদ্রা ইউনিট",
        "commonunits": "সাধারণ ইউনিট",
        "searchunits": "ইউনিট অনুসন্ধান করুন",
        "units": "ইউনিট",
        "from": "থেকে",
        "to": "পর্যন্ত",
        "value": "মান",
        "speed": "গতি",
        "addedtofavorites": "প্রিয়তে যোগ করা হয়েছে",
        "removed": "অপসারণ করা হয়েছে",
        "source": "উৎস: ইউরোপিয়ান সেন্ট্রাল ব্যাংক (Frankfurter)",
        "source2": "উৎস: কয়েনগেকো",
        "invalidinput": "অবৈধ মান",
        "radiation": "বিকিরণ",
        "light": "আলোকসজ্জা",
        "language": "ভাষা",
        "data": "ডেটা",
        "copied": "কপি করা হয়েছে",
        "unitOnCopy": "কপি করার সময় একক",
        "unitOnCopyInfo": "কপি করা মানের সাথে একক দেখান: 120 km/h",

        "unit_speed": "গতি",
        "unit_weight": "ওজন",
        "unit_length": "দৈর্ঘ্য",
        "unit_time": "সময়",
        "unit_temperature": "তাপমাত্রা",
        "unit_volume": "আয়তন",
        "unit_shoe_size": "জুতার আকার",
        "unit_data_size": "ডেটা আকার",
        "unit_data_transfer_speed": "ডেটা স্থানান্তর গতি",
        "unit_pressure": "চাপ",
        "unit_power": "ক্ষমতা",
        "unit_torque": "টর্ক",
        "unit_currency": "মুদ্রা",
        "unit_area": "ক্ষেত্রফল",
        "unit_crypto_beta": "ক্রিপ্টো (beta)",
        "unit_energy": "শক্তি",
        "unit_shares": "অনুপাত / সমানুপাত",
        "unit_viscosity_dynamic": "সান্দ্রতা (গতিশীল)",
        "unit_viscosity_kinematic": "সান্দ্রতা (গতিজ)",
        "unit_angles": "কোণ",
        "unit_electric_current": "বৈদ্যুতিক প্রবাহ",
        "unit_electric_resistance": "বৈদ্যুতিক রোধ",
        "unit_numeral_system": "সংখ্যা পদ্ধতি",
        "unit_magnetomotive_force": "চুম্বকীয় মোটরের বল",
        "unit_magnetic_field_strength": "চুম্বকীয় ক্ষেত্র শক্তি",
        "unit_magnetic_flux": "চুম্বকীয় ফ্লাক্স",
        "unit_image_resolution": "ছবির রেজোলিউশন",
        "unit_inductance": "আবেশ",
        "unit_charge": "চার্জ",
        "unit_linear_charge": "রৈখিক চার্জ ঘনত্ব",
        "unit_volume_charge": "আয়তন চার্জ ঘনত্ব",
        "unit_surface_charge": "পৃষ্ঠ চার্জ ঘনত্ব",
        "unit_magnetic_flux_density": "চুম্বকীয় ফ্লাক্স ঘনত্ব",
        "unit_radiation": "বিকিরণ",
        "unit_radiation_activity": "বিকিরণ কার্যকলাপ",
        "unit_radiation_exposure": "বিকিরণ এক্সপোজার",
        "unit_radiation_absorbed": "বিকিরণ – শোষিত ডোজ",
        "unit_linear_current": "রৈখিক বর্তমান ঘনত্ব",
        "unit_surface_tension": "পৃষ্ঠ টান",
        "unit_flow_rate": "প্রবাহ হার",
        "unit_concentration_solution": "ঘনত্ব (সমাধান)",
        "unit_mass_flux_density": "ভর প্রবাহ ঘনত্ব",
        "unit_luminance": "আলোকসজ্জা",
        "unit_luminous_intensity": "আলোকসজ্জা তীব্রতা",
        "unit_luminous_flux": "আলোকসজ্জা ফ্লাক্স",
        "unit_illuminance": "আলোকসজ্জা",
        "unit_frequency": "ফ্রিকোয়েন্সি",
        "unit_fuel_consumption": "জ্বালানি খরচ",
        ]
    
    private let fa: [String: String] = [ // Dari (Persiska)
            "settings": "تنظیمات",
            "otherapps": "برنامه‌های دیگر",
            "univertfeedback": "بازخورد یونیورت",
            "givefeedback": "ارسال بازخورد",
            "checkoutunivert": "برنامه یونیورت را بررسی کنید!",
            "sharetheapp": "اشتراک‌گذاری برنامه",
            "ratetheapp": "امتیاز به برنامه",
            "about": "درباره",
            "processing...": "در حال پردازش...",
            "purchasecouldntrestore": "هیچ خریدی قابل بازیابی نبود",
            "restorefailed": "بازیابی ناموفق بود",
            "purchaserestored": "خرید شما بازیابی شد",
            "restorepurchase": "بازیابی خرید",
            "advancedunitsunlocked": "واحدهای پیشرفته باز شدند",
            "unlockadvancedunits": "یونیورت پرو",
            "advancedunits": "واحدهای پیشرفته",
            "cancel": "لغو",
            "favoritescleared": "موارد دلخواه پاک شدند",
            "clear": "پاک کردن",
            "clearfavorites?": "آیا می‌خواهید موارد دلخواه ذخیره‌شده خود را پاک کنید؟",
            "clearfavorites": "پاک کردن موارد دلخواه",
            "favorites": "موارد دلخواه",
            "comma": "جداکننده اعشاری ویرگول",
            "darkmode": "حالت تاریک",
            "appearance": "ظاهر",
            "notaddedfavorites": "هنوز هیچ مورد دلخواهی اضافه نکرده‌اید",
            "purchasefailed": "خرید ناموفق بود، لطفا دوباره تلاش کنید",
            "thanksforpurchase": "از خرید شما متشکریم!",
            "loading...": "در حال بارگذاری...",
            "getaccess": "با یک خرید یک‌باره به تمام واحدهای پیشرفته دسترسی پیدا کنید",
            "fluid": "سیال",
            "electricity": "برق",
            "magnetism": "مغناطیس",
            "monetaryunits": "واحدهای پولی",
            "commonunits": "واحدهای رایج",
            "searchunits": "جستجوی واحدها",
            "units": "واحدها",
            "from": "از",
            "to": "به",
            "value": "مقدار",
            "speed": "سرعت",
            "addedtofavorites": "به موارد دلخواه اضافه شد",
            "removed": "حذف شد",
            "source": "منبع: بانک مرکزی اروپا (Frankfurter)",
            "source2": "منبع: CoinGecko",
            "invalidinput": "ورودی نامعتبر",
            "radiation": "تابش",
            "light": "روشنایی",
            "language": "زبان",
            "data": "داده",
            "copied": "کپی شد",
            "unitOnCopy": "واحد هنگام کپی",
            "unitOnCopyInfo": "نمایش واحد همراه با مقدار کپی‌شده: ۱۲۰ کیلومتر/ساعت",

            "unit_speed": "سرعت",
            "unit_weight": "وزن",
            "unit_length": "طول",
            "unit_time": "زمان",
            "unit_temperature": "دما",
            "unit_volume": "حجم",
            "unit_shoe_size": "سایز کفش",
            "unit_data_size": "حجم داده",
            "unit_data_transfer_speed": "سرعت انتقال داده",
            "unit_pressure": "فشار",
            "unit_power": "توان",
            "unit_torque": "گشتاور",
            "unit_currency": "ارز",
            "unit_area": "مساحت",
            "unit_crypto_beta": "کریپتو (beta)",
            "unit_energy": "انرژی",
            "unit_shares": "نسبت / تناسب",
            "unit_viscosity_dynamic": "ویسکوزیته (دینامیک)",
            "unit_viscosity_kinematic": "ویسکوزیته (سینماتیک)",
            "unit_angles": "زوایا",
            "unit_electric_current": "جریان الکتریکی",
            "unit_electric_resistance": "مقاومت الکتریکی",
            "unit_numeral_system": "سیستم عددی",
            "unit_magnetomotive_force": "نیروی محرکه مغناطیسی",
            "unit_magnetic_field_strength": "شدت میدان مغناطیسی",
            "unit_magnetic_flux": "شار مغناطیسی",
            "unit_image_resolution": "وضوح تصویر",
            "unit_inductance": "القای مغناطیسی",
            "unit_charge": "بار الکتریکی",
            "unit_linear_charge": "چگالی بار خطی",
            "unit_volume_charge": "چگالی بار حجمی",
            "unit_surface_charge": "چگالی بار سطحی",
            "unit_magnetic_flux_density": "چگالی شار مغناطیسی",
            "unit_radiation": "تابش",
            "unit_radiation_activity": "فعالیت تابشی",
            "unit_radiation_exposure": "دوز تابش (مواجهه)",
            "unit_radiation_absorbed": "تابش – دوز جذب شده",
            "unit_linear_current": "چگالی جریان خطی",
            "unit_surface_tension": "کشش سطحی",
            "unit_flow_rate": "نرخ جریان",
            "unit_concentration_solution": "غلظت (محلول)",
            "unit_mass_flux_density": "چگالی شار جرمی",
            "unit_luminance": "درخشندگی",
            "unit_luminous_intensity": "شدت روشنایی",
            "unit_luminous_flux": "شار نوری",
            "unit_illuminance": "روشنایی",
            "unit_frequency": "فرکانس",
            "unit_fuel_consumption": "مصرف سوخت",
        ]

        private let ti: [String: String] = [ // Tigrinja
            "settings": "ቅንብራት",
            "otherapps": "ካልኦት ኣፕሊኬሽናት",
            "univertfeedback": "ምብዳህ Univert",
            "givefeedback": "ምብዳህ ሃብ",
            "checkoutunivert": "ኣፕሊኬሽን Univert ርአ!",
            "sharetheapp": "ኣፕሊኬሽን ኣካፍል",
            "ratetheapp": "ኣፕሊኬሽን ደረጃ ሃብ",
            "about": "ብዛዕባ",
            "processing...": "ይሰርሕ ኣሎ...",
            "purchasecouldntrestore": "ዝተዓድገ ነገር ክምለስ ኣይክኣለን",
            "restorefailed": "ምምላስ ኣይተዓወተን",
            "purchaserestored": "ምዕዳግካ ተመሊሱ ኣሎ",
            "restorepurchase": "ምዕዳግ መልስ",
            "advancedunitsunlocked": "ዝማዕበሉ ክፍሊታት ተኸፊቶም",
            "unlockadvancedunits": "Univert PRO",
            "advancedunits": "ዝማዕበሉ ክፍሊታት",
            "cancel": "ኣሰርዝ",
            "favoritescleared": "ዝተፈተውቲ ተሰሪዞም",
            "clear": "ኣጥፍእ",
            "clearfavorites?": "ዝተቐመጡ ዝተፈተውቲ ከተጥፍእ ትደሊዶ?",
            "clearfavorites": "ዝተፈተውቲ ኣጥፍእ",
            "favorites": "ዝተፈተውቲ",
            "comma": "ኮማ ዓሰርተዊ መፋርቕ",
            "darkmode": "ጸሊም ሞድ",
            "appearance": "መልክዕ",
            "notaddedfavorites": "ክሳብ ሕጂ ዝተፈተውቲ ኣይወሰኽካን",
            "purchasefailed": "ምዕዳግ ኣይተዓወተን፣ እንደገና ፈትን",
            "thanksforpurchase": "ንዕዳግኻ የቐንየልና!",
            "loading...": "ይጽዕን ኣሎ...",
            "getaccess": "ብሓንሳብ ምዕዳግ ናብ ኩሎም ዝማዕበሉ ክፍሊታት መእተዊ ረኸብ",
            "fluid": "ፈሳሲ",
            "electricity": "ኤሌክትሪክ",
            "magnetism": "ማግኔቲዝም",
            "monetaryunits": "ናይ ገንዘብ ክፍሊታት",
            "commonunits": "ንጹር ክፍሊታት",
            "searchunits": "ክፍሊታት ድለ",
            "units": "ክፍሊታት",
            "from": "ካብ",
            "to": "ናብ",
            "value": "ዋጋ",
            "speed": "ፍጥነት",
            "addedtofavorites": "ናብ ዝተፈተውቲ ተወሲኹ",
            "removed": "ተወጊዱ",
            "source": "ምንጪ: ባንክ ማእከላይ ኤውሮጳ (Frankfurter)",
            "source2": "ምንጪ: CoinGecko",
            "invalidinput": "ዘይቅዱስ ዋጋ",
            "radiation": "ጨረር",
            "light": "ብርሃን",
            "language": "ቋንቋ",
            "data": "ዳታ",
            "copied": "ተቐድቀደ",
            "unitOnCopy": "ዝተቐደደ ግንዛቤ ብመዓልቲ",
            "unitOnCopyInfo": "ኣብ ቅዳሕ ዝተቐደደ ዋጋ መዓልቲ ርእዩ፡ 120 km/h",

            "unit_speed": "ፍጥነት",
            "unit_weight": "ክብደት",
            "unit_length": "ቁመት",
            "unit_time": "ግዜ",
            "unit_temperature": "ሙቐት",
            "unit_volume": "ስፍሓት",
            "unit_shoe_size": "ቁጽሪ ሰንዓል",
            "unit_data_size": "ዓቐን ዳታ",
            "unit_data_transfer_speed": "ፍጥነት ምስግጋር ዳታ",
            "unit_pressure": "ግፊት",
            "unit_power": "ሓይሊ",
            "unit_torque": "ቶርኪ",
            "unit_currency": "ገንዘብ",
            "unit_area": "ስፍሓት",
            "unit_crypto_beta": "ክሪፕቶ (beta)",
            "unit_energy": "ሃይሊ",
            "unit_shares": "ምምዝዛን / ምትእስሳር",
            "unit_viscosity_dynamic": "ቪስኮሲቲ (ዲናሚክ)",
            "unit_viscosity_kinematic": "ቪስኮሲቲ (ኪነማቲ)",
            "unit_angles": "ኣንግልታት",
            "unit_electric_current": "ኤሌክትሪካዊ ፍሰት",
            "unit_electric_resistance": "ኤሌክትሪካዊ ተጻዋርነት",
            "unit_numeral_system": "ስርዓት ቁጽሪ",
            "unit_magnetomotive_force": "ማግኔቶሞቲቭ ሓይሊ",
            "unit_magnetic_field_strength": "ጥንካረ ማግኔቲካዊ ስፍራ",
            "unit_magnetic_flux": "ማግኔቲካዊ ፍሉክስ",
            "unit_image_resolution": "ውሳነ ስእሊ",
            "unit_inductance": "ኢንዳክታንስ",
            "unit_charge": "ክፍሊ",
            "unit_linear_charge": "ውፍረት ሊኒያዊ ክፍሊ",
            "unit_volume_charge": "ውፍረት ስፍሓት ክፍሊ",
            "unit_surface_charge": "ውፍረት ወለል ክፍሊ",
            "unit_magnetic_flux_density": "ውፍረት ማግኔቲካዊ ፍሉክስ",
            "unit_radiation": "ጨረር",
            "unit_radiation_activity": "ንጥፈት ጨረር",
            "unit_radiation_exposure": "ንጨረር ምግላጽ",
            "unit_radiation_absorbed": "ጨረር – ዝተዋሕጠ መጠን",
            "unit_linear_current": "ውፍረት ሊኒያዊ ፍሰት",
            "unit_surface_tension": "ውጥረት ወለል",
            "unit_flow_rate": "መጠን ፍሰት",
            "unit_concentration_solution": "ምጥምጣፍ (መፍትሒ)",
            "unit_mass_flux_density": "ውፍረት ፍሰት ክብደት",
            "unit_luminance": "ብርሃናዊነት",
            "unit_luminous_intensity": "ጥንካረ ብርሃን",
            "unit_luminous_flux": "ፍሉክስ ብርሃን",
            "unit_illuminance": "ብርሃናዊነት",
            "unit_frequency": "ፍሪኩዌንሲ",
            "unit_fuel_consumption": "ናይ ነዳዲ ፍጆታ",
        ]

        private let nl: [String: String] = [ // Nederländska
            "settings": "Instellingen",
            "otherapps": "Andere apps",
            "univertfeedback": "Univert feedback",
            "givefeedback": "Feedback geven",
            "checkoutunivert": "Bekijk de Univert app!",
            "sharetheapp": "Deel de app",
            "ratetheapp": "Beoordeel de app",
            "about": "Over",
            "processing...": "Bezig...",
            "purchasecouldntrestore": "Geen aankopen konden worden hersteld",
            "restorefailed": "Herstellen mislukt",
            "purchaserestored": "Je aankoop is hersteld",
            "restorepurchase": "Aankoop herstellen",
            "advancedunitsunlocked": "Geavanceerde eenheden ontgrendeld",
            "unlockadvancedunits": "Univert PRO",
            "advancedunits": "Geavanceerde eenheden",
            "cancel": "Annuleren",
            "favoritescleared": "Favorieten gewist",
            "clear": "Wissen",
            "clearfavorites?": "Wil je je opgeslagen favorieten wissen?",
            "clearfavorites": "Favorieten wissen",
            "favorites": "Favorieten",
            "comma": "Komma decimaal scheidingsteken",
            "darkmode": "Donkere modus",
            "appearance": "Uiterlijk",
            "notaddedfavorites": "Je hebt nog geen favorieten toegevoegd",
            "purchasefailed": "Aankoop mislukt, probeer opnieuw",
            "thanksforpurchase": "Bedankt voor je aankoop!",
            "loading...": "Laden...",
            "getaccess": "Krijg toegang tot alle geavanceerde eenheden met een eenmalige aankoop",
            "fluid": "Vloeistof",
            "electricity": "Elektriciteit",
            "magnetism": "Magnetisme",
            "monetaryunits": "Monetaire eenheden",
            "commonunits": "Veelvoorkomende eenheden",
            "searchunits": "Zoek eenheden",
            "units": "Eenheden",
            "from": "Van",
            "to": "naar",
            "value": "Waarde",
            "speed": "Snelheid",
            "addedtofavorites": "Toegevoegd aan favorieten",
            "removed": "Verwijderd",
            "source": "Bron: Europese Centrale Bank (Frankfurter)",
            "source2": "Bron: CoinGecko",
            "invalidinput": "Ongeldige waarde",
            "radiation": "Straling",
            "light": "Verlichting",
            "language": "Taal",
            "data": "Data",
            "copied": "Gekopieerd",
            "unitOnCopy": "Eenheid bij kopiëren",
            "unitOnCopyInfo": "Toon eenheid bij gekopieerde waarde: 120 km/h",

            "unit_speed": "Snelheid",
            "unit_weight": "Gewicht",
            "unit_length": "Lengte",
            "unit_time": "Tijd",
            "unit_temperature": "Temperatuur",
            "unit_volume": "Volume",
            "unit_shoe_size": "Schoenmaat",
            "unit_data_size": "Gegevensgrootte",
            "unit_data_transfer_speed": "Gegevensoverdrachtsnelheid",
            "unit_pressure": "Druk",
            "unit_power": "Vermogen",
            "unit_torque": "Koppel",
            "unit_currency": "Valuta",
            "unit_area": "Oppervlakte",
            "unit_crypto_beta": "Crypto (bèta)",
            "unit_energy": "Energie",
            "unit_shares": "Verhouding / Proportie",
            "unit_viscosity_dynamic": "Viscositeit (dynamisch)",
            "unit_viscosity_kinematic": "Viscositeit (kinematisch)",
            "unit_angles": "Hoeken",
            "unit_electric_current": "Elektrische stroom",
            "unit_electric_resistance": "Elektrische weerstand",
            "unit_numeral_system": "Nummeriek systeem",
            "unit_magnetomotive_force": "Magnetomotorische kracht",
            "unit_magnetic_field_strength": "Magnetische veldsterkte",
            "unit_magnetic_flux": "Magnetische flux",
            "unit_image_resolution": "Afbeeldingsresolutie",
            "unit_inductance": "Inductantie",
            "unit_charge": "Lading",
            "unit_linear_charge": "Lineaire ladingsdichtheid",
            "unit_volume_charge": "Volumetrische ladingsdichtheid",
            "unit_surface_charge": "Oppervlakteladingsdichtheid",
            "unit_magnetic_flux_density": "Magnetische fluxdichtheid",
            "unit_radiation": "Straling",
            "unit_radiation_activity": "Stralingsactiviteit",
            "unit_radiation_exposure": "Stralingsblootstelling",
            "unit_radiation_absorbed": "Straling – Geabsorbeerde dosis",
            "unit_linear_current": "Lineaire stroomdichtheid",
            "unit_surface_tension": "Oppervlaktespanning",
            "unit_flow_rate": "Stroomsnelheid",
            "unit_concentration_solution": "Concentratie (oplossing)",
            "unit_mass_flux_density": "Massastroomdichtheid",
            "unit_luminance": "Luminantie",
            "unit_luminous_intensity": "Lichtsterkte",
            "unit_luminous_flux": "Lichtstroom",
            "unit_illuminance": "Verlichtingssterkte",
            "unit_frequency": "Frequentie",
            "unit_fuel_consumption": "Brandstofverbruik",
        ]
    
    private var tables: [String: [String: String]] {
        [
            "sv": sv, // Svenska
            "en": en, // Engelska
            "de": de, // Tyska
            "es": es, // Spanska
            "fr": fr, // Franska
            "he": he, // Hebreiska
            "zh": zh, // Kinesiska
            "ar": ar, // Arabiska
            "ru": ru, // Ryska
            "ja": ja, // Japanska
            "it": it, // Italienska
            "tr": tr, // Turkiska
            "ko": ko, // Koreanska
            "pl": pl, // Polska
            "el": el, // Grekiska
            "pt": pt, // Portugisiska
            "hi": hi, // Hindi
            "bn": bn, // Bengali
            "fa": fa, // Farsi
            "ti": ti, // Tigrinja
            "nl": nl, // Nederländska
        ]
    }

    func get(_ key: String) -> String {
        tables[language]?[key] ?? key
    }
}
